### ISSUE TITLE
Lines for translation

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#1]
To prevent the issue of many people translating the same lines, you may indicate and reserve lines in the comment below the ones you'd be contributing on so that others would skip those lines. :)

Please check the wiki page for reminders before sending your pull requests  :)

**Comment by Disorrder** [comment]
Does it mean, you will create new repository for each language? :)

**Comment by Dynanaut** [comment]
Translated Line #7 to "What's the fuss?"

**Comment by salvabas** [comment]
Revised already made translations in ETC_en.tsv

Lines 39, 114, 115, 116, 140, 141, 149, 152, 153, 157, 160, 161, 194, 195, 203, 206, 207

**Comment by AEJung** [comment]
I'll reserve lines [988](https://github.com/Treeofsavior/EnglishTranslation/blob/master/ETC_en.tsv#L988) - [1001](https://github.com/Treeofsavior/EnglishTranslation/blob/master/ETC_en.tsv#L1001) for now and start on them later today !

EDIT: Many of these lines are missing words and/or aren't sequential and therefore are not accurately translatable. Is this intentional? This is also the cause of the nonsensical English fragments that people are running into in the translated file.

**Comment by shimekops** [comment]
Revised Line 968: Word "Equipments" is incorrect. 'Equipment' has no plural for as it is a non-countable noun

**Comment by Nagoda** [comment]
I am skimming through QUEST_LV_0100_en.tsv and making a first pass at revising the translated English text starting at around line 200 and working through the rest of the document, currently at about line 400. Mostly correcting obvious grammar mistakes and rewriting things to make them sound more natural if there is an easy fix.

I'm skipping over any chunks that are missing a lot of translation, anything unintelligible, or anything that needs more context (like seeing it in the game) to know how it should read.

**Comment by kunomi** [comment]
Fluent English, native korean speaker here. Going through line 600- onwards in the ETC file. Hoping to get through to 700. Fixing some translations along the way.

**Comment by Cloudpiercer** [comment]
Going through lines 550-570 for the ETC file.

**Comment by Clariche** [comment]
Hello, I'm another native Korean, who does translate professionally time to time. I'll take line 400~599, filling in whichever lines that aren't translated in between those line numbers.

**Comment by ericxinui** [comment]
translated lines 820, 828, 844, 846, 851, 860.

**Comment by wolfpaq777** [comment]
I'm going to start taking a look at lines 1-100 of SKILL _en.tsv (was there intended to be a space in the file name?)

I'm a native English speaker, beginner Korean so I'll be mostly looking for grammar corrections, although I'll also look for things like "German property" -> "poison attribute"

**Comment by TheStargrazer** [comment]
I fixed some of the grammar and capitalization errors and reread ETC_en.tsv lines 1-502. I decided to leave the more vague lines as they are so someone can provide a better translation.

**Comment by TheStargrazer** [comment]
Same thing as before, Revised translation for ETC_en.tsv this time with lines 503-1001.
