### ISSUE TITLE
The "This line doesn't exist at all!" Thread.

### ISSUE THREAD

**Issue by vtange** [Treeofsavior/EnglishTranslation#1003]
I gave myself a mini heart attack when I noticed that the QUEST line ids were no longer matching with the line count for notepad++. Then I remembered QUEST 1198 literally doesn't exist. Not even in {memo X} form.

To avoid this issue, could we have an issue thread/wiki page that details what lines literally don't exist so people can be sure they didn't just wipe a line off the file? OK Thanks :)

**Comment by Soukyuu** [comment]
You gave me a mini heart attack as well when I was checking your PR :P 
I think the safest bet would be to look at the Korean file, they're supposed to be in sync. You could also just look at the official repo and see if the line is missing there too.

**Comment by BloodHeartless** [comment]
lol  I m listening heart attack...  and the file really don t exist.
