### ISSUE TITLE
Item drat  and Fixed arrow

### ISSUE THREAD

**Issue by BloodHeartless** [Treeofsavior/EnglishTranslation#1010]
Hi, I was searching for mistranslations and I found this.. That is not exactly a mistranslation. But the word "drat" is not commonly understandable to all. 

ITEM_20150317_001201    Drat Gloves 
ITEM_20150317_001202    Drat Sandals 
ITEM_20150317_001203    Drat Pants 
ITEM_20150317_001204    Drat Robe 
ITEM_20150317_001205    Drat Leather Gloves 

ITEM_20150317_001201    드라트 글로브
ITEM_20150317_001202    드라트 샌들
ITEM_20150317_001203    드라트 팬츠
ITEM_20150317_001204    드라트 로브
ITEM_20150317_001205    드라트 레더 글로브

And in korean, the meaning .. i dont know . Come from  Hydra? 

And here we go to this item 

ITEM_20150717_005577    Fixed Arrow   

to change to "Fixed Bow"

ITEM_20150717_005577    고정활

**Comment by Sunaries** [comment]
'Drat' is correct. Not everything in games have to have a meaning. The developers probably came up with 'Drat' because it sounds good?

Fixed Bow is indeed the item's name.

**Comment by BloodHeartless** [comment]
but there is a meaning to drat, and some people use like a interjection to annoyance, a disgust interjection .

**Comment by Soukyuu** [comment]
darkhershel is right, "drat" is pretty much an equivalent to "damn", "shit", etc.

**Comment by BloodHeartless** [comment]
yes, indeed . That's why I found it strange in a item name.

**Comment by imcgames** [comment]
Yup, in Korean, Drat was used more like a name without a separate meaning to it. 
But for English version, I guess we can change its spelling or change it to something else similar if its meaning is too disturbing to use just as an item name. 
i.e.  Draght, Dratt, Drate, Drata, etc
We're open to suggestions :smile:

**Comment by BloodHeartless** [comment]
I liked drato, but it's can be dratt ( if you want to leave the same pronounced) .
And remeber the Fixed Bow

**Comment by Soukyuu** [comment]
Should probably go with "Dratt" to keep the pronunciation.
What does "fixed" in this context mean? Rigid?

**Comment by ghost** [comment]
I'd go with "Dratt" as well.

I believe "fixed" means it's mounted or emplaced somewhere.

**Comment by imcgames** [comment]
Fixed in 'Fixed Bow' means fastened, locked, stationed,

**Comment by jmaxun** [comment]
Meaning of Drat
drat
a mild expression of anger or annoyance.
"“Drat!” said Mitchell, kicking the fence"

**Comment by imcgames** [comment]
Alright, we go with 'Dratt' then :smile:

**Comment by Sunaries** [comment]
I created a pull request https://github.com/Treeofsavior/EnglishTranslation/pull/1027 which is pending. This issue can be closed. :)

**Comment by BloodHeartless** [comment]
And the fixed bow?

**Comment by Sunaries** [comment]
> And the fixed bow?

I now did. :) Thanks.
