### ISSUE TITLE
[!] Many instances of $NoData after the recent data reset.

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#1070]
Greetings @imcgames,

On September 25, the test server had its data reset and after this process, we've come to the discovery that new lines have been added, resulting in $NoData. For instance, tooltips for many skills are empty. 

![GitHub Logo](http://i.imgur.com/yPDS9NI.png)

Please update the _kor files, so that we can resume, because I don't think we can send in new pull requests right now because of this. Thank you. :smile:

**Comment by TentuZero** [comment]
This is occurring to all lines so far and for some reason tooltips as well.

**Comment by imcgames** [comment]
Seems like some translation related files were changed in our latest patch. 
It will need a patch on the client side to be fixed (github files are fine, no changes needed there)
so we'll have to wait for the next KCBT patch to have the problem resolved.  :sob: 
(FYI, the next patch is scheduled to be next week, after the holidays in Korea)
We apologize for the inconvenience caused.

**Comment by Sunaries** [comment]
> Seems like some translation related files were changed in our latest patch. 
> It will need a patch on the client side to be fixed (github files are fine, no changes needed there)
> so we'll have to wait for the next KCBT patch to have the problem resolved.  :sob: 
> (FYI, the next patch is scheduled to be next week, after the holidays in Korea)
> We apologize for the inconvenience caused.

Ah, I see. Thanks for answering. I did notice that after today's minor patch (18:10~18:40), some instances of $NoData were resolved. Hopefully quest-related dialogue is untouched so that we can continue working on it. :smiley:

**Comment by Sunaries** [comment]
@imcgames It seems to be fixed, but I am not certain. However, I do know that there are new lines and we would like to receive an update to the **_kor** files. :) Thanks.

**Comment by imcgames** [comment]
We'll check on it when we resume to office after the holidays on Wednesday :wink:
