### ISSUE TITLE
Word "colleague" 

### ISSUE THREAD

**Issue by BloodHeartless** [Treeofsavior/EnglishTranslation#1141]
The word "colleague" can be changed to another?To "partner" or "pal" for example ?

**Comment by terrapin47** [comment]
Why?  It generally is correct in context, where I've seen it.

**Comment by BloodHeartless** [comment]
the context is like partner. But the word colleague is .. how can I say? Old school.

**Comment by terrapin47** [comment]
It's something you say in a more professional context.  Like a co-worker.

**Comment by BloodHeartless** [comment]
I know that. But this word is used to soldiers and civilians. To soldiers, i think, that word is too empty.. they have a brotherhood, not only a mere collegiality. To civilians, ok.

**Comment by Flevalt** [comment]
"To soldiers, i think, that word is too empty"
That's a good point. Soldiers are indeed brothers in arms and have a very close relationship during war times. Going through life and death situations together, it's hard to develop a stronger bond than through that.
It's not like they are just doing some office work together or standing guard at a safe place. 
They are going through many harsh and nerve-wrecking emotional situations during battle.

I doubt most people pay attention to such small formalities. But I also doubt most people will read anything story-related that's not in the UI and descriptions, so with that logic one might as well argue that most of the translation wouldn't be necessary.
So I'm all for this heart-warming little change.

**Comment by Ragunaga** [comment]
We should not change colleague everywhere, as it's generally good in its current context, but if you see something like you pointed out with soldiers it should probably be changed to a more fitting term such as partner.

Whatever fits the context.

**Comment by BloodHeartless** [comment]
many people don't read the history, but for the others, a good role playing =) @Flevalt

**Comment by BloodHeartless** [comment]
I think that too @Ragunaga
