### ISSUE TITLE
Subquest, [Complete] tags

### ISSUE THREAD

**Issue by terrapin47** [Treeofsavior/EnglishTranslation#1148]
Regarding the green [Complete] tags present for subquests, it's a bit confusing currently.  The tag says "complete", but the quest is not complete, and it's also colored green, implying that you've successfully completed it already.

![complete tag image](https://images.discordapp.net/.eJwFwQEKwjAMAMC_9AFNlsXS7DehEyfadCwZA8W_e_dN5_FOS9oidl8A1qe3cazZ56xdP8P08txGB43QtvW7hUPFeapSiFkQiaWAiFQUvBFxFeKpwGkvG5fl3R7p9we-Ox_e.2d5HgyOTruQzxlSgOUOZ5u__Wos.png?width=400&height=178&format=webp)

The subquest also disappears from the list when it is complete.  I see these lines in ETC alongside [Complete], however:
ETC_20150317_002053 [In Progress]
ETC_20150317_002054 [Incomplete]
ETC_20150317_002055 [Complete]

Is this a bug?  Should the tag be showing [Incomplete] when you first take the main quest, [In Progress] when you start the subquest, and [Complete] when you've completed it?

Also, the first quest item is always spaced improperly ( the spacing on the lines in the files isn't to blame ).  As you can see in the image, the quests are laid out like:
[tag]$questname
[tag] $questname
[tag] $questname
With no space between the tag and questname on the first item.

**Comment by Sunaries** [comment]
@imcgames Yeah, I've noticed this too. Wrong tags?
