### ISSUE TITLE
Problem regarding QUEST_LV_0200.tsv

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#1155]
Hello @imcgames 

I want to edit the QUEST_LV_0200.tsv file, but it is too big. The edit button won't show up.

**Comment by Ragunaga** [comment]
You have to change it locally and push it online using the git command line. No other way sadly, unless they split it into two or more files, which isn't that great an idea.

**Comment by ttgmichael** [comment]
looks like @Sunaries will be using git bash, so I guess this issue is moot? :)
