### ISSUE TITLE
Illegal quoting issue

### ISSUE THREAD

**Issue by aentan** [Treeofsavior/EnglishTranslation#118]
Just wanna check:

in `ETC.tsv`

Github reports `We can make this file beautiful and searchable if this error is corrected: Illegal quoting in line 4563.`

`ETC_20150317_004563     퀘스트Name = "`

There is a single double quote. There are other lines like that too. Wanna understand what is the purpose of the quote.

**Comment by imcgames** [comment]
The above mentioned line was removed from the updated file but other lines with single double quotes still exist. Unfortunately, there are various uses for the quotes in game texts so it can't really be removed.
