### ISSUE TITLE
Many $NoData is comeback after this days patch

### ISSUE THREAD

**Issue by unicorn00** [Treeofsavior/EnglishTranslation#1242]
Greetings @imcgames 

This is chn version translation team, at the patchs about oct.5 we've found the new text can't show properly when use language pack.

We guess that if skill's tooltip are considered to item's tooltip

![20151016114641](https://cloud.githubusercontent.com/assets/11720639/10533439/eb972858-73fb-11e5-875e-d946821c4edb.jpg)
![20151016114615](https://cloud.githubusercontent.com/assets/11720639/10533440/eb9d7316-73fb-11e5-84e8-9744e47a7ea7.jpg)

**Comment by imcgames** [comment]
Thank you for a bug report. It was already known issue to us. :+1: 
It is going to be fix on 2nd iCBT.
