### ISSUE TITLE
Regarding translation of '전이 틈새' 

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#1243]
@imcgames 

In the Demon Prison area, there is a lot of dialogue mentioning **전이 틈새** which is currently translated as **space of the metastasis**. It has been brought to my attention that 'metastasis' can mean: "The spread of cancerous cells from one area of the body to other areas." 

Do you want to keep the current translation or use an alternative? The contributors of the Discord group have given the following alternatives:
- Dimensional Gap 
- Dimensional Crack
- Dimensional Space
- Dimensional Rift
- Hollow Rift
- Chasm
- Abyss
- Limbo
- Oblivion
- gap in the barrier

**Comment by imcgames** [comment]
I think Dimensional Crack is good to express the "전이 틈새". :+1:

**Comment by Sunaries** [comment]
Alright, that settles it then. I'll change it in my upcoming PR of Demon Prison today. Thank you. :smile:
