### ISSUE TITLE
Missing translation lines - maybe focus these for now?

### ISSUE THREAD

**Issue by laurencee** [Treeofsavior/EnglishTranslation#1262]
Hey Guys, I've noticed that there has been a primary focus on sorting out machine translations and performing grammar/correctness checks on existing translations.

I think at this point it might be good to try and sort out the remaining missing translation lines which I have taken note of below, there are quite a few entirely missing lines.

| File Name | Missing Lines |
| --- | --- |
| ~~ETC.tsv~~ | ~~ETC_20151001_014833 -> ETC_20151016_015920~~ |
| ~~ITEM.tsv~~ | ~~ITEM_20151001_007083 -> ITEM_20151016_007275~~ |
| QUEST.tsv | QUEST_20151016_002706 -> QUEST_20151022_002909 |
| QUEST_LV_0100.tsv | QUEST_LV_0100_20151016_009577 -> QUEST_LV_0100_20151016_011237 |
| QUEST_LV_0200.tsv | QUEST_LV_0200_20151016_009681 -> QUEST_LV_0200_20151016_009838 |
| ~~SKILL.tsv~~ | ~~SKILL_20150918_005235 -> SKILL_20151016_005337~~ |
| ~~UI.tsv~~ | ~~UI_20151016_001822~~ |
| ~~[NEW] ETC.tsv~~ | ~~ETC_20151022_015921 -> ETC_20151022_016490~~ |
| [NEW] Item.tsv | ITEM_20151022_007276 -> ITEM_20151022_008363 |
| ~~[NEW] SKILL.tsv~~ | ~~SKILL_20151022_005357 -> SKILL_20151022_005506~~ |

**Comment by ttgmichael** [comment]
Most of these lines were recently added: 20151016 means they were added 2015, Oct 16. Just 3 days ago. 

We will try to translate them as fast as we can. Thanks for the heads up though xD.

**Comment by laurencee** [comment]
Oh that's rather obvious after you mentioned it, haha.

Thanks for all the hard work, everyone appreciates what you guys have been doing.

**Comment by BloodHeartless** [comment]
so many blank files 

ITEM_20150317_002681    {memo X}  
ITEM_20150317_002683    {memo X} 
ITEM_20150317_002687    {memo X} 
ITEM_20150317_002689    {memo X} 
ITEM_20150317_002691    {memo X} 
ITEM_20150317_002709    {memo X} 
ITEM_20150317_002711    {memo X} 
ITEM_20150317_002713    {memo X} 
ITEM_20150317_002715    {memo X} 
ITEM_20150317_002928    {memo X} 
ITEM_20150317_002929    {memo X} 
ITEM_20150317_003516    {memo X} 
ITEM_20150317_003517    {memo X} 
ITEM_20150317_003527    {memo X} 
ITEM_20150317_003528    {memo X} 
ITEM_20150317_003654    {memo X} 
ITEM_20150317_003656    {memo X} 
ITEM_20150317_003660    {memo X} 
ITEM_20150317_003663    {memo X} 
ITEM_20150317_003664    {memo X} 
ITEM_20150317_003675    {memo X} 
ITEM_20150317_003676    {memo X} 
ITEM_20150317_003688    {memo X} 
ITEM_20150317_003689    {memo X} 
ITEM_20150317_003690    {memo X} 
ITEM_20150317_003692    {memo X} 
ITEM_20150317_003694    {memo X} 
ITEM_20150317_003696    {memo X} 
ITEM_20150317_003702    {memo X} 
ITEM_20150317_003711    {memo X} 
ITEM_20150317_003712    {memo X} 
ITEM_20150317_003713    {memo X} 
ITEM_20150317_003718    {memo X} 
ITEM_20150317_003754    {memo X} 
ITEM_20150317_003775    {memo X}
ITEM_20150317_003910    {memo X} 
ITEM_20150317_003911    {memo X} 
ITEM_20150317_003912    {memo X} 
ITEM_20150317_003913    {memo X} 
ITEM_20150317_003915    {memo X} 
ITEM_20150317_003920    {memo X} 
ITEM_20150317_003922    {memo X} 
ITEM_20150317_003925    {memo X} 
ITEM_20150317_003927    {memo X} 
ITEM_20150323_003979    {memo X} 
ITEM_20150323_003985    {memo X} 
ITEM_20150323_003987    {memo X} 
ITEM_20150323_003989    {memo X} 
ITEM_20150323_003990    {memo X} 
ITEM_20150323_003993    {memo X} 
ITEM_20150323_004037    {memo X} 
ITEM_20150323_004038    {memo X} 
ITEM_20150323_004039    {memo X} 
ITEM_20150323_004040    {memo X} 
ITEM_20150323_004041    {memo X} 
ITEM_20150323_004045    {memo X} 
ITEM_20150323_004049    {memo X} 
ITEM_20150323_004051    {memo X} 
ITEM_20150323_004052    {memo X} 
ITEM_20150323_004053    {memo X} 
ITEM_20150323_004055    {memo X} 
ITEM_20150323_004056    {memo X} 
ITEM_20150323_004057    {memo X} 
ITEM_20150323_004059    {memo X} 
ITEM_20150323_004061    {memo X} 
ITEM_20150323_004062    {memo X} 
ITEM_20150323_004063    {memo X} 
ITEM_20150323_004065    {memo X} 
ITEM_20150323_004066    {memo X} 
ITEM_20150323_004068    {memo X} 
ITEM_20150323_004083    {memo X} 
ITEM_20150323_004087    {memo X} 
ITEM_20150323_004090    {memo X} 
ITEM_20150323_004091    {memo X} 
ITEM_20150323_004092    {memo X} 
ITEM_20150323_004093    {memo X} 
ITEM_20150323_004094    {memo X} 
ITEM_20150323_004095    {memo X} 
ITEM_20150323_004099    {memo X} 
ITEM_20150323_004100    {memo X} 
ITEM_20150323_004101    {memo X} 
ITEM_20150323_004103    {memo X} 
ITEM_20150323_004106    {memo X} 
ITEM_20150323_004107    {memo X} 
ITEM_20150323_004108    {memo X} 
ITEM_20150323_004109    {memo X} 
ITEM_20150323_004111    {memo X} 
ITEM_20150323_004112    {memo X} 
ITEM_20150323_004115    {memo X} 
ITEM_20150323_004116    {memo X} 
ITEM_20150323_004118    {memo X} 
ITEM_20150323_004120    {memo X} 
ITEM_20150323_004122    {memo X} 
ITEM_20150323_004124    {memo X} 
ITEM_20150323_004129    {memo X} 
ITEM_20150323_004131    {memo X} 
ITEM_20150323_004132    {memo X} 
ITEM_20150323_004133    {memo X} 
ITEM_20150323_004134    {memo X} 
ITEM_20150323_004136    {memo X} 
ITEM_20150323_004137    {memo X} 
ITEM_20150323_004138    {memo X} 
ITEM_20150323_004139    {memo X} 
ITEM_20150323_004140    {memo X} 
ITEM_20150323_004141    {memo X} 
ITEM_20150323_004144    {memo X} 
ITEM_20150323_004145    {memo X} 
ITEM_20150323_004146    {memo X} 
ITEM_20150323_004147    {memo X} 
ITEM_20150323_004148    {memo X} 
ITEM_20150323_004149    {memo X} 
ITEM_20150323_004150    {memo X} 
ITEM_20150323_004152    {memo X} 
ITEM_20150323_004155    {memo X} 
ITEM_20150323_004156    {memo X} 
ITEM_20150323_004157    {memo X} 
ITEM_20150323_004158    {memo X} 
ITEM_20150323_004160    {memo X} 
ITEM_20150323_004162    {memo X} 
ITEM_20150323_004164    {memo X} 
ITEM_20150323_004169    {memo X} 
ITEM_20150323_004191    {memo X} 
ITEM_20150323_004202    {memo X} 
ITEM_20150323_004203    {memo X} 
ITEM_20150323_004213    {memo X} 
ITEM_20150323_004215    {memo X} 
ITEM_20150323_004242    {memo X} 
ITEM_20150401_004496    {memo X} 
ITEM_20150401_004497    {memo X} 
ITEM_20150401_004511    {memo X} 
ITEM_20150401_004515    {memo X} 
ITEM_20150406_004593    {memo X} 
ITEM_20150406_004599    {memo X} 
ITEM_20150406_004602    {memo X} 
ITEM_20150714_005322    {memo X} 
ITEM_20150717_005687  
ITEM_20150717_005695  
ITEM_20150918_006056  
ITEM_20150918_006072
ITEM_20150918_006074
ITEM_20150918_006193  
ITEM_20150918_006194  
ITEM_20150918_006335
ITEM_20150918_006510
ITEM_20150918_006580
ITEM_20150918_006675
ITEM_20150918_006771  
ITEM_20150918_006772  
ITEM_20150918_006773  
ITEM_20150918_006775  
ITEM_20150918_006776
ITEM_20150918_006778
ITEM_20150918_006876    {memo X}
ITEM_20150918_006877    {memo X}
ITEM_20150918_006878  
ITEM_20150918_006881

**Comment by BloodHeartless** [comment]
ETC_20150317_008005 N/A ~ ETC_20150317_008055   N/A
ETC_20150317_008078 N/A ~/ ETC_20150317_008100  N/A
ETC_20150714_012806  
ETC_20150714_012964 N/A
ETC_20150714_013107 N/A ~  ETC_20150714_013113  N/A

**Comment by laurencee** [comment]
Yes that's a good pickup @darkhershel, it's unfortunate that there are junk text and memo tags on those lines as that caused me to overlook them (I'm sure it caused others to overlook them as well).

**Comment by laurencee** [comment]
Keeping my original post up to date with new lines to translate
