### ISSUE TITLE
IMC commit reverted a few translations

### ISSUE THREAD

**Issue by laurencee** [Treeofsavior/EnglishTranslation#1285]
c06cd574ee322176e02d59fa52dfe448a91235e2 seems to have reverted a few translations which I assume was not intended.

These are the ones I found:
~~https://github.com/Treeofsavior/EnglishTranslation/commit/c06cd574ee322176e02d59fa52dfe448a91235e2#diff-1ce585bbcef9e8542ae39ca04b3143afR14144~~ fixed by @Sunaries 
https://github.com/Treeofsavior/EnglishTranslation/commit/c06cd574ee322176e02d59fa52dfe448a91235e2#diff-1ce585bbcef9e8542ae39ca04b3143afR14305
https://github.com/Treeofsavior/EnglishTranslation/commit/c06cd574ee322176e02d59fa52dfe448a91235e2#diff-1ce585bbcef9e8542ae39ca04b3143afR14322
https://github.com/Treeofsavior/EnglishTranslation/commit/c06cd574ee322176e02d59fa52dfe448a91235e2#diff-1ce585bbcef9e8542ae39ca04b3143afR15010

On a side note, I don't understand what the point was of adding memo X to all those lines is.

**Comment by ttgmichael** [comment]
IMC places memo X on lines that aren't used in the game anymore, so we can focus on translating lines that are in the game.

**Comment by laurencee** [comment]
Ah ok that's pretty good usage of it.
