### ISSUE TITLE
Paladin's Restoration: SP Recovery 

### ISSUE THREAD

**Issue by poonwu** [Treeofsavior/EnglishTranslation#1310]
Is the SP Recovery affecting only paladin himself? or is it also on his allied?

The language is kind of ambiguous, can anyone with good Korean help confirm this to me?
https://github.com/Treeofsavior/EnglishTranslation/blob/master/SKILL_kor.tsv#L4676
https://github.com/Treeofsavior/EnglishTranslation/blob/master/SKILL.tsv#L4676

**Comment by ttgmichael** [comment]
It's for the paladin only. Character means strictly character. If the description did something with allies, it would say so. I checked the Korean line. :)

Hope this helps.

**Comment by poonwu** [comment]
@ttgmichael Thanks

**Comment by ttgmichael** [comment]
@poonwu actually, I talked to some people who play paladin and I might be wrong from my previous statement.

The line itself is correct: the SP recovery bonus is applied to a character. But the bonus can also be applied to allies when the character is within the Paladin's [Restoration] aoe.

Sorry for any confusion I may have caused ><

**Comment by ttgmichael** [comment]
@poonwu 
If this issue is solved, can you close it? Thanks! :)

**Comment by poonwu** [comment]
@ttgmichael 
I have no authority to close this issue.

**Comment by ttgmichael** [comment]
@poonwu  huh, that's interesting. There should be a button below for you to close it.

@imcgames this issue is solved, you may close it. :)
