### ISSUE TITLE
Doppelsoldner and Schwarze Reiter class names

### ISSUE THREAD

**Issue by TOSBase** [Treeofsavior/EnglishTranslation#133]
Refering to https://github.com/Treeofsavior/EnglishTranslation/wiki/2.1.%20Class

I'd like to make some suggestions regarding 2 class names wich are based on german names:

1) Doppelsoldner should be changed to Doppelsöldner
It should be Doppelsöldner (see http://en.wikipedia.org/wiki/Doppelsöldner). I understand that the ö is not very common for most people but the goddesses also have names that include special characters like Giltinė so it should either removed for all names or kept for all names.
If you really don't want to use the ö for some reason please switch to oe. It was like this before and it's also like this on the Nexon page but got changed here on github for some reason. The official replacement for ö would be oe but ö should be used if possible.

Quote from wikipedia: In other languages that do not have the letter as part of the regular alphabet or in limited character sets such as ASCII, O-umlaut is frequently replaced with the digraph "oe".

But I think in TOS there is technical reason not to use the ö.

Source:
http://en.wikipedia.org/wiki/Germanic_umlaut
http://en.wikipedia.org/wiki/Ö

2) Schwarze Reiter should be changed to Schwarzer Reiter
I think this translation is based on this wikipedia page: http://en.wikipedia.org/wiki/Reiter
it states: “Schwarze Reiter”—literally, "black riders"
"Schwarze Reiter" is a plural. All other classes use the singular (e.g. Archer instead of Archers) so the correct name would be "Schwarzer Reiter" (with an additional "r") as this means "black rider" instead of "black riders". It's strange to see this one class name as plural.

**Comment by imcgames** [comment]
Both classes mentioned above were changed in the Wiki Reference :)
