### ISSUE TITLE
A bit of question about Doppelsoeldner

### ISSUE THREAD

**Issue by merrun** [Treeofsavior/EnglishTranslation#1351]
Is the name really doppelsoeldner? or doppelsoldner? ..since from what I know the real meaning for the name is "doppel" for double and "sold" for ...sold/pay? ..why there's an e in there?

**Comment by ttgmichael** [comment]
Because doppelsoeldner is the correct way of spelling Doppelsöldner without the accented o (ö). 

See below for a closed issue as we've discussed the spelling before :)
https://github.com/Treeofsavior/EnglishTranslation/issues/510

**Comment by merrun** [comment]
oh ...should've realized that its already there
