### ISSUE TITLE
Usage of "$"

### ISSUE THREAD

**Issue by sunlightning** [Treeofsavior/EnglishTranslation#1368]
Do I need to put it always before editing?

Like item001 $Empty Helmet

Or item001 Empty Helmet?

Thanks.

**Comment by Sunaries** [comment]
The '$ system' is a method created on our end. We always put it in front of the text. 
This is a mark meant to show that the line has been reviewed and shouldn't necessarily be edited again. Again, this is something the contributors of the English version have come up with.

**Comment by sunlightning** [comment]
Oh, alright. Thanks. :+1:
