### ISSUE TITLE
Consistency: Cathedral, Church, or Chapel?

### ISSUE THREAD

**Issue by JuneGame** [Treeofsavior/EnglishTranslation#1391]
There has been an inconsistency with regards to Tenet Chapel and Great Cathedral. Both seem to use the same characters "성당" but ended up with different translations.

Tenet (테넷) Chapel (성당)
Great (대) Cathedral (성당)

Attached is a screenshot from both the Collection and World Map UI showing different translations on Tenet.

![0002](https://cloud.githubusercontent.com/assets/4481575/11453608/61c55f78-964c-11e5-9a02-9584d0033d72.png)
![0001](https://cloud.githubusercontent.com/assets/4481575/11453610/67fc7c0a-964c-11e5-9383-6dcf739be268.png)

**Comment by ttgmichael** [comment]
성당 is a pretty broad term that just means (Holy/Sacred Hall). In English, we call that a Church/Chapel/Cathedral, usually based on size. 

Tenet Chapel is the correct term both according to the wiki and by context (the area of the place is pretty small).

Great Cathedral is the correct term (though not on the wiki) if you've been there, you'll realize the area is much more wider than Tenet Chapel. So size-wise, Cathedral is more fitting.

I'll fix the Tenet Cathedral lines as you posted. Thanks for pointing this out! :+1:

**Comment by JuneGame** [comment]
Thank you for the clarification on the matter, but upon doing some further reading, I think "Chapel" does NOT suit the case of both places by definition. Tenet is far larger than a chapel, if anything.

![0001](https://cloud.githubusercontent.com/assets/4481575/11454745/eb8c931c-9673-11e5-85b6-6ed632520572.png)

Church seems to be the mediator between the two.

![0002](https://cloud.githubusercontent.com/assets/4481575/11454754/38f926e2-9674-11e5-8694-160e3f4ce3c9.png)

Great Cathedral is justified not only because of its size but also because of Bishop Aurelius' presence and authority over the area.

![0003](https://cloud.githubusercontent.com/assets/4481575/11454762/70527850-9674-11e5-86d3-43a3da4ac565.png)

Source: Merriam-Webster

**Comment by vtange** [comment]
IMC decided this to be "Chapel" at their wiki here: https://github.com/Treeofsavior/EnglishTranslation/wiki/2.2.%20Map

IMO, "Tenet Chapel" rings better than "Tenet Church". And having another "Cathedral" will just make things confusing/repetitive.

Some things are just better left as is.

**Comment by ttgmichael** [comment]
This will be up to @imcgames, since I believe they chose the names for these areas. 

Relative to the Great Cathedral, I would say the Tenet 'building' is small. By definition though, I agree 'chapel' might not be the best word for the name; Tenet Church would work. It'll be an easy switcheroo if IMC is ok with the change to Tenet Church. :+1:

**Comment by ttgmichael** [comment]
The PR that changes Tenet Chapel to Tenet Church has been merged. So I believe you can close this issue now @DoubleN94 :+1:

**Comment by JuneGame** [comment]
All right. :+1:
