### ISSUE TITLE
Which English dialect?

### ISSUE THREAD

**Issue by Wolvaroo** [Treeofsavior/EnglishTranslation#199]
Should we be trying to stay consistent with either UK or American English?

I assume most international media these days opt to use American English, but I've noticed quite a few gaols (jail) in the translation. Are these placed with intent or just a machine translation by-product?

with open source translations maybe it would be best to do a series of find and replace edits near the end of the process to be consistent.

**Comment by imcgames** [comment]
We did not use UK English with intent unless specified in reference or used as names.
It could be machine or user translations and it isn't an issue for now but if we had to choose, then it'd be more conventional to opt for American English for most parts. :)
