### ISSUE TITLE
Current progression - English TOS

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#218]
Hello @imcgames ,

Is it possible for you to give more screenshots or a video in-game to show progress in the English TOS client using the recent localized files? Because I would love to see it since there are a few contributors who've done a good job. 

Is the idea of editing awkwardly translated text, where you locate your cursor on the text and press CTRL+SHIFT with a mouse click to edit while ingame? It would certainly make this a lot easier for me. 

Thank you.

**Comment by imcgames** [comment]
Check out the main page for a preview of real-time text edit function! :smile:

**Comment by vegax87** [comment]
Amazing!

**Comment by Sunaries** [comment]
Thank you @imcgames - It looks good and I cannot wait to use this! :smiley: 
Especially since editing in Github takes too long for me since I get this sort of lag/slowness when editing.

**Comment by Nagoda** [comment]
The real-time editing tool looks really powerful!

**Comment by Gardosen** [comment]
I just want to mention,

I tested the OTC system on the client while the CBT2 and this system is still a bit buggy. 
- Some labels are overlapping others so you cant target them.
- Some labels are not clickable with the OTC System
- Some labels are showing wrong labelkeys and/or wrong label texts.

I would be happy to see a fixed version of it in the obt :)

translation the client by using this OTC system is even for a non korean speaking person pretty easy up to a specific point.

Kind regards
Gardosen from TOSBase.com

**Comment by imcgames** [comment]
Real time editing was not meant to be used in Korea CBT2 or more so, not in the Korean version of the game so it probably was not the latest one.
And yes, It still needs some further tests and fixes which we are working on but thank you for your feedback.  :smile:
