### ISSUE TITLE
"Chance of receiving additional exp of 50%." is vague/awkward.

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#223]
The text "Chance of receiving additional exp of 50%." appears in quite a few items and is kind of vague/awkward.

Should be...
"50% chance of receiving additional exp."
or...
"Chance of receiving 50% additional exp."
depending on the intended meaning.

@imcgames please advise and I can submit a patch to fix it!

**Comment by imcgames** [comment]
Sure, you can fix and send us pull requests :)

**Comment by dlam** [comment]
@imcgames which of the two is the intended meaning?

Is there a chance to get 50% more experience (i.e., gain 150% of the normal xp given) or is there a 50% chance to gain an unknown amount of experience?

**Comment by imcgames** [comment]
It most probably would mean the former (chance to get 50% more EXP) but just to be sure, which line are you referring to?

**Comment by dlam** [comment]
There are many lines, but for example:

ITEM_20150317_001884    경험치를 +30 상승시켜 줍니다. 일정 확률로 50%의 경험치를 추가 획득할 수 있습니다. 마우스 오른쪽 클릭으로 사용합니다

ITEM_20150317_001884    Adds 30 EXP. Chance of receiving additional EXP of 50%. Right-click to use.

**Comment by imcgames** [comment]
Yup, it means there's a chance to get 50% more EXP
