### ISSUE TITLE
Awkward names for proper nouns in item wiki.

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#226]
The [wiki](https://github.com/Treeofsavior/EnglishTranslation/wiki/2.4.%20Item) provides some official translations for proper nouns in this game. I was going through some item translations and realized that some of the English translations are awkward (or not even in English).

This issue is to address those awkward translations with @imcgames for their actual intended names, so I can proceed with correcting the English translations in /blob/master/ITEM_en.tsv.

As a cautionary note: I don't speak Korean, so I don't know if these particular names were intentionally chosen for some reason. A lot of these fixes were made by looking at in-game icons and searching up the official translations for a more common name.

Here's a full list of things to be changed on the Item wiki page:

Notes:
- Some translations have alternative translations / notes in parentheses.

| Korean | Original Translation | New Translation |
| --- | --- | --- |
| 바루날레샤 | Varnalesa | Burdock Root |
| 발래리요나스 | Valerijonas | Valerian |
| 초브랠리스 | Ciobrelis | Thyme |
| 워시스 | Uosis | Ash |
| 아말라스 | Amalas | Mistletoe |
| 아비에테 | Aviete | Raspberry |
| 기슬로티스 | Gyslotis | Plantain |
| 요나졸레 | Jonazole | Saint John's Wort (alt. Hypericum) |
| 마이루나스 | Mairunas | Marjoram |
| 라무넬레 | Ramunele | Daisy |
| 라오도넬리스 | Raudonelis | Oregano |
| 살라위야스 | Salavijas | Sage |
| 딜겔레 | Dilgele | Nettle |
| 매두스 | Medus | Honey (alt. Honeycomb) |
| 누켈라 | Nukela | Nukella (inconsistency with in-game icon) |
| 성수 | Purewater | Holy Water |
| 포포리온 고기 | Popolion | Popolion Meat |
| 해독제 | Andidote | Antidote |
| 글래스몰 카드 | Glass_Mole Card | Glass Mole Card |
| 붉은 케파의 결정 | Crystal of Red_Kepa | Crystal of Red Kepa |
| 베스퍼의 무게추 | Weitght Clapper of Vesper | Weight of Vesper |
| 멘티우드의 날개 | Mentiwood | Mentiwood Wing |
| 밀납 | Batik | Wax |
| 날개 개구리의 핵 | Wing Flog | Core of Flying Flog (alt. Core of Flying Frog, Core of Winged Frog) |
| 베카라베의 껍질 | Vekarabe | Beetle Shell (alt. Vekarabe Shell) |
| 티피오의 꽃술 | Stamen Tipio | Tipio Stamen |
| 판토 창날 | Panto Spear Shape | Panto Spear Pattern (alt. Panto Spear Blade) |
| 유리조각 | Glass Slice | Glass Fragment |
| 떡갈나무 | Oka Tree | Oak Tree |
| 떡갈나무 목재 | Oka Lumber | Oak Lumber |
| 콜리플라워의 줄기 | Stem of Cauliflower | Cauliflower Stem (alt. Cauliflower Root) |
| 보드킨포인트 애로우 | Bodkinpoint Arrow | Bodkin Point Arrow |
| 웬디고 송곳니 | Wendigo Canine | Wendigo Fang |
| 금괴 | Glod Bar | Gold Bar (alt. Gold Bullion) |
| 수은 | Sliver | Mercury (alt. Quicksilver) |
| 나무 말뚝 | Tree Stake | Log |
| 거친 뼛가루 | Rough Bone Waste | Coarse Bone Powder |
| 브람블의 뿔 | Thron of Bramble | Thorn of Bramble |

**Comment by imcgames** [comment]
Thank you for your suggestions :+1: 
Some are not named in English intentionally but for those applicable, 
we have taken your suggestions and updated our wiki page with it :smile:

**Comment by dlam** [comment]
Thanks!
