### ISSUE TITLE
Inputting extended ASCII characters in translations.

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#227]
There should be a note on the wiki page on how to do this.

For example, the character, ö, is used in multiple places, but I'm not sure how to encode this in the translations. Generally, developers would use HTML codes like {&ouml;}... but the scheme is dependent on the project.

@imcgames could we get an official response on how to do this?

EDIT: Forgot to escape the HTML code sample...

**Comment by imcgames** [comment]
Our plan is not to use special characters as much as possible since it could be inconvenient for players. 
You can stick to using plain English characters :)

**Comment by dlam** [comment]
Okay, thanks for following up.
