### ISSUE TITLE
Typos in official translations for items in wiki.

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#228]
I was sweeping through ITEM_en.tsv and applying the official translations for proper nouns when I noticed some typos.

These are the changes that need to be made:

| Original | New |
| --- | --- |
| Kepachieftain Card | Kepa Chieftain Card |
| Minotaurs Card | Minotaur Card |
| Hone of Panto | Horn of Panto |
| Hron of Drake | Horn of Drake |
| Vubbe Pickax | Vubbe Pickaxe |
| Stoneorca Piece | Stone Orca Piece |
| Pawndel'S Shaft | Pawndel's Shaft |
| Clawof Galok | Galok Claw (consistency with other claw items) |
| Balck Market Seal | Black Market Seal |
| Orihalcon Ore | Orichalcum Ore |
| Blood Stone | Bloodstone |

**Comment by imcgames** [comment]
Thank you, Wiki updated :smile:

**Comment by dlam** [comment]
Thanks!
