### ISSUE TITLE
Skype group / Hipchat / IRC chat channel for fan translators?

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#232]
Any interest / possibility in opening a chat channel for all the fan translators and the devs responsible for this project?

It would help resolve git conflicts, overlap work, and might be nice to have a real-time way to contact the devs.

Also, it would help build some community and give us a place to complain and talk about how great we are with each other.

**Comment by TOSBase** [comment]
There is a Tree of Savior IRC channel at globalgamers.net
The webchat is available at https://webchat.globalgamers.net/?channels=treeofsavior

vegax87 is in there quite often, maybe some devs other translators want to join, too? ^^

**Comment by imcgames** [comment]
There may be some issues for us to open a chat channel but we do plan to have a section dedicated for translators when we open our official forums so please hang on until then :)

In the mean time, you may continue to use this 'Issues' function of github if you need us in the discussion, or @TOSBase 's suggestion also sounds good for a chat channel amongst translators :+1:

**Comment by Gardosen** [comment]
@imcgames : is there any email where we (TOSBase) can talk to your team directly?
we would like to support you on this translation project by writing a special tool, that users can translate the client more easy. (so far we saw in your video, and also expereicned by our self that only the notepad or notepad++ is used. we have an idea for a automized tool, which makes it realy easy for people to translate the lines :)

would be cool to know if there is an email address where we can write to to get in touch with your team. :)

Kind regards
Gardosen from TOSBase.com

**Comment by imcgames** [comment]
@Gardosen Is it something that can't be discussed in public here in Github? Since the tool will be used by users in the end, it would also be nice to have it discussed in open with other translators too. 

Otherwise, you can send emails to tos@imc.co.kr as mentioned in our official homepage :smile:

**Comment by Gardosen** [comment]
@imcgames We can also discuss it here :)

as Flash and me where testing the OTC in the CBT2 (i still hope you are not angry about it, we where just curious about the system ^^ ) we noticed that the tool which will be used for the translation is a predefined tool by the user (we tested it with excel, notepad++ and notepad).
we also noticed that we had to check for the string by our self. so we tought about the following:

whenever a user is clicking on a text to see the label, the labelkey for this text should be copied into the clipboard of the system + the defined tool should open. on this point we would like to jump in and support you. we were translating Ragnarok Online 2 in the past on a high level as we where able to decode all files and wrote our own tool for this to make it easier for us. so we have quiet a lot of experience on creating userfriendly translation tools.

the idea for the tool would look like this
![img_14052015_182210](https://cloud.githubusercontent.com/assets/415867/7660596/ce2262b6-fb4b-11e4-8ce6-ee7400f0f835.png)

whenever a user would checkout a label and the tool would open up, the tool would directly jump to the correct file and to the correct line. (in the current OTC System this is currently missing as it uses normal editors, but would increase the translation efficiency extremly) this would only work if the client would save the selected label to the clipboard.

the tool also would offer a checkbox system (Show Original Text on the right side) for showing the base language from where the user is translating the client into his language.
the save button on the right side is for increasing the speed to be able to save the files after a change without the need of a shortcut or going to File->Save

we have some more ideas for a colaborated cloud saving system but this is still in development. the general idea would be that every change a user is doing on our tool, if he activates the cloud-teamwork-system, gets saved to a central system.

if you like the idea and want to know more about it, contact me or Flash and we will get in touch with your team.

Kind regards
Gardosen from TOSBase.com

**Comment by imcgames** [comment]
@Gardosen Thank you for showing such interest in the tool.
We really appreciate those efforts that our fans show us!  :+1: 

As for the edit tool, you mentioned that the current system does not jump to the correct file and correct line but actually, it is supposed to, if you're using notepad++ (should work like the gif in the main page - opens the corresponding file and line). So if that's the problem you encountered, then maybe the newer version would be the solution?

In the official version (which I think wasn't in CBT2?), there will be a separate file that designates a predefined tool as you mentioned, and when the translation is selected from client, you will be directed to that line from the translation file.
(line number and file path is used as reference instead of the label key) 

It is possible that the system that you tested wasn't fully functional in the CBT2 as it wasn't the English version so for now, I would suggest that you try the official version of the tool first when we have our English client in the future.
Maybe you can have your tool compatible with our system instead and designate your tool for your use? :smile: 
Btw, the collaborated cloud saving system among your tool users sounds awesome so keep up the great work guys :clap:

**Comment by TOSBase** [comment]
@imcgames if you already have a way to tell the program which line should be opened than that's good and we'll try to use the same input for our tool, so users can easily switch between notepad++ and our tool and everything will be compatible to eachother. I looked at the notepad++ documentation and found the -n parameter to open the file at that line.
So I assume the way the client starts notepad++ (or the tool defined in the config) is by
C:...\notepad++.exe -n150 ETC_en.tsv
to open the file ETC_en.tsv on line 150? It would help us to know these paramters to make our tool compatible.

**Comment by imcgames** [comment]
@TOSBase  Yes, that is correct  :+1: 
We use [Path] for tsv path, [Line] for line no., [Column] for column.
Therefore, for notepad++ it'd actually be C:...\notepad++.exe "[Path]" -n[Line]
But please note that the game is still in development stage so anything may be subject to change if necessary :smile:
