### ISSUE TITLE
조악한 intended meaning.

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#236]
I'm currently proofreading some of the existing translations in ITEM_en.tsv.

From my understand, 조악한 -> coarse; poor; inferior; crude.

The existing translations are inconsistent between "Crude" and "Mediocre", and has potential for awkwardness within context. i.e., Using a recipe to craft a "Mediocre Falchion" and receiving a "Crude Falchion" as a result.

@imcgames what is the intended meaning for 조악한 ?

Some examples of existing translations:
- 조악한 글라디우스 -> Crude Gladius
- 조악한 샴시르 -> Mediocre Shamshir
- 조악한 시미터 -> Mediocre Scimitar
- 조악한 카스카라 -> Crude Kaskara

Also, it might make sense to update the wiki with an example of 조악한 usage.

**Comment by imcgames** [comment]
As commented in https://github.com/Treeofsavior/EnglishTranslation/issues/237 ,  조악한 equipments are no longer used as names so you may skip those lines :)
