### ISSUE TITLE
[Video] CBT2 gameplay with some of our translations :)

### ISSUE THREAD

**Issue by vegax87** [Treeofsavior/EnglishTranslation#252]
Thanks to Flash of TOSBase, you can see here CBT2 gameplay with a half-English client so we can fix the missing translations or the wrong ones.

https://www.youtube.com/playlist?list=PLZmwVtJXg551uyb5Rlsd9qdVtwkiMpaiw

English UI (Fan Translation): https://www.youtube.com/watch?v=OlBo9ixl5Z8

**Comment by Nagoda** [comment]
Really neat to see it in action.

I noticed that there's a text-wrapping issue on the ability point screen where the game is starting a new line of text in the middle of a word. You can scrub to 2:46 to see, "abilities" near top is split, and "strengthen" near the bottom.

**Comment by Sunaries** [comment]
That's funny to see some of my translations in that video. Some sentences need to be aligned differently or the font size needs to be smaller. 

This makes me want to play the game even more and use that new tool that @imcgames developed to edit text in game. I experience slow and lag when editing the current files on Github.

**Comment by vegax87** [comment]
added part 2 to the open post

**Comment by vegax87** [comment]
added English UI - Fan translation video in my open post, it was recorded during the last day of CBT2
