### ISSUE TITLE
Deletion of translation files

### ISSUE THREAD

**Issue by hasenbanck** [Treeofsavior/EnglishTranslation#286]
@imcgames : Why did you deleted some translation files with the last commits? Those files where not nearly finished and QUEST_LV_0100_en.tsv needed heavy translation checking and still a lot of editing.

It would be nice if you could use the commit message to explain why you are doing things like this. Do you intent to re-add them in a different structure? Do you considered them as "finished"?

**Comment by imcgames** [comment]
Since CBT2 is over, QUEST_LV_100 will be updated later on with more contents and fixes from CBT2. And while the work is in progress, it would not be efficient for the file to keep changing as it might cause conflicts so we deleted the file from the repository for now. We plan to add it back in the future with some updates :)

**Comment by hasenbanck** [comment]
This is a bad idea, in terms how GIT works. You have now deleted the whole history of the files. We won't know in the future who has touched which line and how the source/target files were changed.

Please refrain from doing so in the future. This approach is MUCH better when using GIT and trying to get the best possible translation quality:
- Open an issue where you state that you are currently reworking the affected files (QUEST_LV_100 in this case).
- Deny every pull request that touches these files. Reference to the issue.
- When you have changed the files in your office and want to merge then back into this repository, simply overwrite the file, this way we will see what content has been changed and which lines we will need to re-translate / re-edit / check.
- Delete the issue.

That way we will keep the history, will see all changed (and can track them for quality checking!) and you can still "freeze" them for that time being.

Please also use the commit comment to explain such changes, so that we have an easier time to work together. Thx!

**Comment by imcgames** [comment]
Thank you for your suggestions. We will try to make use of notice/issue/comments when we do this next time.
As for file history, it will also be added back when the files are added  :)

**Comment by hasenbanck** [comment]
Yes, the file history is fine, even when re-adding the file. But the line history is broken.

Let's view the line history with the help of "blame" for ETC:
https://github.com/Treeofsavior/EnglishTranslation/blame/master/ETC_en.tsv

Now let's view the line history for the QUEST_LV_0100:
https://github.com/Treeofsavior/EnglishTranslation/blame/c15fd566512242a320fe5cab2d9dc6babfbff394/QUEST_LV_0100_en.tsv

You are shadowing now all the old changes and touch every line. That makes QA a little bit more complicated (Since we need to move through the whole file again).

If you merge the changes for the CBT2 results, please re-add the old file first and then merge the new file. That way we will at least see what the CBT2 line changes are.

**Comment by hasenbanck** [comment]
I will close the issue, so we don't clutter the issue list.
