### ISSUE TITLE
Double translations to resolve

### ISSUE THREAD

**Issue by hasenbanck** [Treeofsavior/EnglishTranslation#295]
Just finished my first check of my tool to help the translation process of ToS. I wrote a small program that scans the files for entries, with the same Korean line but different English translations. As a result I found two conflicts, which need to be resolved by a translator:

Conflict one:
ETC_20150317_005246
ETC_20150323_009673

Conflict two:
ETC_20150317_006248
ETC_20150414_010918

**Comment by Sunaries** [comment]
Hello~

**ETC_20150317_005246**
Get rid of Merge who restricted the soul.

**ETC_20150323_009673**
Defeat the Merge that entrapped the soul!

These two should be: "_Defeat the soul binding Merge!_" 
Merge is a boss monster. Odd name for a monster, but okay.

**ETC_20150317_006248**
Highlanders are tough fighters and use two-hand swords. They make enemies ccollide with each other or terrains so they are great for handling multiple enemies.

**ETC_20150414_010918**
Highlanders are tough fighters who use two-handed swords. They make enemies ccollide with each other or terrains so they are great for handling multiple enemies.

These two should be: "_Highlanders are tough fighters who uses two-handed swords. They make enemies collide with each other or terrains, so they are great for handling multiple enemies._"
