### ISSUE TITLE
Tree of Savior on Steam Greenlight? Is it real?

### ISSUE THREAD

**Issue by vegax87** [Treeofsavior/EnglishTranslation#305]
IMCGames can you confirm if you have published ToS on Steam Greenlight?

http://steamcommunity.com/sharedfiles/filedetails/?id=441500423

**Comment by Sunaries** [comment]
Interesting..

**Comment by vegax87** [comment]
I hope it's real because it has been Greenlit ( approved by Steam community ) in 10 hours, more or less

**Comment by imcgames** [comment]
Yes, it is and thank you very much for your support :+1: 
Please hang on and wait for further announcements!

**Comment by Sunaries** [comment]
@imcgames Thank you very much for clarifying. I am anticipating your further announcement. :-)

**Comment by Psychaox** [comment]
@imcgames  Thank you and thumbs up! Players from TAIWAN are so desperately anticipating your following news !

**Comment by vegax87** [comment]
Thank you IMCGames! :smiley:

**Comment by xLethologica** [comment]
@imcgames Will it be F2P on Steam ?

**Comment by oraclexzf** [comment]
@xLethologica hopefully not, then it has a good chance of being pay2win. 

If valve/nexon or who ever hosts this game puts their own greed above yet another great Korean game, then don't be surprised if a bunch of decide to work on a emulator.

**Comment by Sunaries** [comment]
@xLethologica @oraclexzf

The game will launch free to play in Korea. It will most likely retain the same payment model in the West. IMCGAMES has said that the game will have different publishers in different regions.
In Korea, the publisher is Nexon Korea.

**Comment by ceddc** [comment]
Great ! :+1:
