### ISSUE TITLE
Quest dialogue translation

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#315]
Do you at IMC Games  want a direct translation for all of the Quest dialogue? I watched a video of a CBT2 ENG translation version of ToS and the dialogue feels clunky and forced, mostly because a lot of what makes sense and is natural in Korean doesn't translate 1:1 perfectly with English. Will there be an opportunity for the translators to see the lines we translate in-game and then be able to tweak the dialogue from there? I can see a huge potential for a much smoother/natural dialogue for quests and NPCs if there was an opportunity to put the dialogue into context (settings, character personalities, etc.).

**Comment by Nagoda** [comment]
There will eventually be a phase where testers will be able to see the game client and edit dialog as it appears using a custom real-time editing tool. 

For the moment, however, we have to do our best with limited context.

**Comment by megaoka** [comment]
Yeah I feel a lot of the story content is hard to edit without context right now. If we were given access to the beta (and optionally the real-time editing tool), it would help a lot.

Even some of the items seem very situational, and without knowing the context it makes it a little difficult to refine the translation.
