### ISSUE TITLE
Royal tomb translation and consistency

### ISSUE THREAD

**Issue by ceddc** [Treeofsavior/EnglishTranslation#321]
Hello there,

Disclaimer : I don't speak or understand a word of korean.

@Sunaries pointed out a misspell about Royal Tomb in this pull : https://github.com/Treeofsavior/EnglishTranslation/pull/312

So, I checked a bit.

There is (case incensitive):
- 12 results of "Royaltomb"
- 35 results of "Royal Tomb"

Seems to be related with this word : 왕릉

This word is present 95 times in the files, but seems to be translated differently : 
- Tomb
- Royal Tomb
- Royal
- King Tomb
- King
- Wang (wang is king in chinese)
- Mausoleum 
- Underground Mausoleum 

What is according to you the correct way to translate it, and to make it consistent ?

Some example are here : 

| Reference | Text | Translation |
| --- | --- | --- |
| ETC_20150317_000165 | 왕릉석기병은 강하고 노련한 중무장 기사도 감당할 정도로 만들어진 마법피조물입니다. | Wang Ling stoneware bottle is creatures of strongly clever heavily armed articles were also made about margin magic. |
| ETC_20150317_000195 | 자카리엘이 남긴 왕릉의 수비시설 중의 하나입니다. | Zasharieru is the one of the defensive facilities king Ling who left. |
| ETC_20150317_000205 | 기원은 왕릉의 시설물이지만 현재는 모든 생명체를 공격하는 오작동 상태입니다. | Origin, but is a facility of the King Mausoleum, now is the malfunction state to attack all creatures. |
| ETC_20150317_000457 | 왕릉에 서식하던 동물이 근래에 마기의 영향을 받아 변형된 몬스터입니다. | Animals that lived in the king tomb, It is a monster that has been deformed in recent years by the influence of the Magi. |
| ETC_20150317_000461 | 왕릉을 수호하기 위해 만들어진 마법피조물이며 약하지만 여신의 힘도 깃들어 마족에게 강한 편입니다. | Is a creature of magic that was created to protect the king's tomb. However, it is the stronger the Asmodian also been rice Goddess of power. |
| ETC_20150317_000465 | 툼싱커를 비롯한 왕릉에 배치된 것들은 특별히 마족의 침입에 강하도록 만들어졌습니다. | Those that have been placed in the king's tomb, including the Tombsinker, it has been made to the river especially for intruding Asmodian. |
| ETC_20150317_000653 | 왕릉 게이트 | Wang Ling Gate |
| ETC_20150317_001196 | 왕릉 1층 | Underground Mausoleum 1st district |
| ETC_20150317_001197 | 왕릉 | Underground Mausoleum |
| ETC_20150317_002414 | 왕릉석등 보호 실패! | Failed to protect royal tombstone lantern |
| ETC_20150317_002417 | 왕릉 파괴 저지 실패! | Failed to prevent destroying the royal tombstone! |
| ETC_20150317_003279 | 왕릉2층 보스 처치 | Get rid of the boss on the 2nd floor of Royal Tomb. |
| ETC_20150317_003286 | 함정으로 왕릉 전사를 유인해 쓰러트리세요! | Lure the Tomb Warriors into the trap and kill them! |
| ETC_20150317_003294 | 왕릉 전사 | Royal Tomb Warriors |
| ETC_20150317_003970 | 지역 왕릉 입구에 세워야 합니다 | You should build it in the entrance of the local tomb |
| ETC_20150317_005022 | 왕릉 석등이 수호자들에게 공격을 받고 있습니다. | The tombstone lanterns are being attacked by the guardians! |
| ETC_20150317_005408 | 왕릉 억제기 | Royal Tomb Suppressor |
| ETC_20150317_005412 | 수호자들로부터 왕릉 석등 보호! | Protect the royal tomb stone lanterns from the guardians! |
| ETC_20150317_005413 | 왕릉비석 | Monument of the Royal Tomb |
| ETC_20150317_006824 | 왕릉 32 | Royal Tomb 32 |
| ETC_20150317_007068 | 왕릉 입구 | Royal Tomb Entrance |
| ETC_20150317_007113 | 왕릉 큐브 | Royal Cube |
| ETC_20150317_007114 | 왕릉비석01 | Royal Tombstone01 |
| ETC_20150317_007116 | 왕릉 석등 | Royal Stone Lentern |
| ETC_20150317_007218 | 왕릉 미니 큐브 | Tomb Mini Cube |
| ETC_20150317_007537 | 왕릉 큐브 근처에서 부우크를 고장내서 왕릉 큐브에 흡수시키기 | Absorb the royal cube to break the Boowook around royal tomb cube. |
| ETC_20150317_007539 | 봉헌함에 왕릉 수호자 동력원 봉헌 | Royaltomb Guard Power Source Consecration to container |
| ETC_20150317_007802 | 왕릉 장치 확인 | Check the royal device |
| ETC_20150317_007968 | 왕릉미션 큐브 세션 | N/A |
| ETC_20150317_009110 | 왕릉 수호자1 | Royal Guard 1 |
| ETC_20150317_009301 | 왕릉 수호 큐브 | Royal Guard Cube |
| ETC_20150317_009304 | 왕릉 마력 억제기 | Tomb Spell Suppressor |
| ETC_20150317_009305 | 왕릉3층 | Royaltomb the third floor |
| ETC_20150317_009313 | 충전된 왕릉 큐브 | Charged Tomb Cube |
| ETC_20150317_009467 | 왕릉 수호 장치 | Royal Tomb Guardian device |
| ETC_20150401_010449 | 왕릉 노역자 숙소 | Underground Mausoleum Workers' Lodge |
| ETC_20150401_010630 | 마기 정화가 완료되었습니다.{nl}왕릉 노역자 숙소에 빛의 기운이 스며듭니다. | Completed purifying Magi. {nl}The energy of light is permeating the Underground Mausoleum Workers Lodge |
| ETC_20150401_010667 | 왕릉 제단 | Underground Mausoleum Altar |
| ETC_20150414_011152 | 왕릉 호위대 병영에서만 사용할 수 있습니다. | Can only be used in within barracks of king's escort. |
| ETC_20150414_011192 | 활성석 효과가 비활성 상태입니다!{nl}왕릉 억제기 사용 설명서로 돌아가 다시 활성화 시키세요. | Active stone is not activated! {nl}Return to Masoleum manually and activate it again. |
| ETC_20150428_011234 | 왕릉 건축자 예배당 | Mausoleum Builder's Chapel |
| ETC_20150428_011346 | 왕릉 비석03(파랑) | Mausoleum Gravestone03 (Blue) |
| ETC_20150428_011517 | 왕릉 건축자 예배당에서만 사용할 수 있습니다. | It can be used only the Tobm Building Chapel. |
| ETC_20150428_011539 | 왕릉 입구로 이동 중 | Moving to the entrance of the Royal Tomb |

**Comment by imcgames** [comment]
Thank you for your suggestion. :+1: 
For now, we will go with Mausoleum or Underground Mausoleum depending on the context :smile:

**Comment by ceddc** [comment]
Thanks,

Is it possible to update the wiki?
https://github.com/Treeofsavior/EnglishTranslation/wiki/2.2.%20Map

| Korean | English |
| --- | --- |
| 왕릉 1층 | Royal Mausoleum 1st district |

**Comment by imcgames** [comment]
Sorry for the confusion but we've decided to change and go for Royal Mausoleum rather than Underground Mausoleum :smiley:

**Comment by khakiout** [comment]
:+1:
