### ISSUE TITLE
Is KR tree of savior delayed? If yes, it'll affect english version?

### ISSUE THREAD

**Issue by blackops2008** [Treeofsavior/EnglishTranslation#324]
Since tree of savior was removed from nexon 2015 releases...

 Source : http://upload2.inven.co.kr/upload/2015/05/14/bbs/i11038658807.jpg

**Comment by vegax87** [comment]
English Version is going to be published on Steam, while Nexon is for Korean players, they're totally different publishers.

**Comment by blackops2008** [comment]
Steam is not publishing yet, steam often is used only as social media and retailer.  And i dont know  if IMC would launch a International version of the game without a korean version of it. So  if korean version will be delayed it could affect the international version release too.

**Comment by vegax87** [comment]
Take a look here: http://steamcommunity.com/sharedfiles/filedetails/?id=441500423

**Comment by blackops2008** [comment]
I did see it bro, But  being greenlit  do not confirm that steam will be publisher. Tibia and wakfu for example  got greenlit but steam isnt  its publisher, just a retailer. It will be the same case with ToS probably.

**Comment by ceddc** [comment]
From here : https://www.reddit.com/r/treeofsavior/comments/3606ye/looks_like_tree_of_savior_will_not_be_released/cr9vfvk

> If you pay close attention to the presentation (http://pdf.irpocket.com/C3659/Q8aV/UUxv/hfxW.pdf), you will see that the slide with the pipeline actually has a footnote that says "**Chart is illustrative _excerpt_ pipeline**", meaning that this is not all the games that will be published. They might have just chose to leave out ToS in this particular presentation..

**Comment by blackops2008** [comment]
its wierd to leave such hyped game out of this chart . it worries me :(

**Comment by ceddc** [comment]
And the best way to help with English version, is to take part and motivate people in this great project ! :wink:

**Comment by blackops2008** [comment]
I just wanted some insight from IMC games , since people from reddit and fansites  are worried about this.

**Comment by Azebu** [comment]
They were on track for late 2015/early 2016 release. As much as I don't like it, having the late 2015 part removed sooner than later is good.
But let's not panic, we should wait for official word from devs, it could be just Korea. And as long as this doesn't affect date of first international beta test, I don't have a problem with this.

**Comment by blackops2008** [comment]
thats why i opened this issue. I want to know if this delay from nexon will affect ToS International.

**Comment by Gardosen** [comment]
Nexon is only the publisher for Korea for Tree of Savior.
they do have nothing todo with the International release.

so this presentation is also obsolete as you would need a presentation from imc games if you want to know more about the ongoing process.
