### ISSUE TITLE
ITEM.tsv and ITEM_en.tsv don't  match up

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#332]
I just noticed that the line numbers don't match up for ITEM.tsv and ITEM_en.tsv.

I was editing 2H Spear strings and line 666 in the Korean file is Two-Handed Spear [Pierce] while that line in the EN file is 667.

**Comment by ceddc** [comment]
There is 2 Item  ITEM_20150317_000707
https://github.com/Treeofsavior/EnglishTranslation/blob/master/ITEM_en.tsv#L643

**Comment by emailboxu** [comment]
Seems like when they merged the patch it didn't delete the unedited line like it was supposed to.

**Comment by emailboxu** [comment]
Found the error and removed the extra line. Fixed.
