### ISSUE TITLE
Slot names?

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#351]
Needed confirmation on what you wanted to put as the various equipment slot names. In one line, for example, you have Hair Slot vs Hat Slot (could even change this to Helmet or Head Slot). If someone could clarify what the name should be standardized to that would be great.

**Comment by Sunaries** [comment]
I left a note in your pull request. It doesn't mention anything of a slot, but it refers the item being simply a hair/head decoration.

**Comment by emailboxu** [comment]
Thanks, fixed that particular issue. If it comes up again I'll make a different issue thread.
