### ISSUE TITLE
Plurals?

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#354]
Going through the various monster drops and am wondering if I need to leave monsters as singular. 

> Looks similar to a bat wing, but is actually a plant stem. Obtained from Dandels.

Makes more grammatical sense since Dandels are (presumably) a common monster and you can farm the said Item (Dandel Wing).

The alternative is to leave them singular:

> Looks similar to a bat wing, but is actually a plant stem. Obtained from Dandel.

which sounds weird. Let me know what you think, I'm currently just pluralizing everything but it won't be hard to undo that in another patch.

**Comment by megaoka** [comment]
Either

> Obtained from Dandel**s**

or

> Obtained from **a** Dandel

will work in this situation. Personally though, I prefer the first. "Obtained from Dandel" should only be used when it's referring to a specific person or object, like a named NPC or Boss.

**Comment by megaoka** [comment]
On a similar note, I have been changing things from "X of Y" to "Y's X" because I think it sounds better and is shorter/neater. Is there any case where we should not have it like this?

e.g. - "Bone of Popolion" -> "Popolion's Bone"

**Comment by emailboxu** [comment]
I switched all of the X of Ys to Y X (Ie, Popolion Bone). Y's X usually refers to a proper noun for Y (ie, emailboxu's post) rather than a generic Y X (ie, dog treat). I figured since all of these strings are generic mobs/not bosses Y X would be better than Y's X. Again this is fairly easy to change. 

I agree that the plurals sound much better for non-NPC/Boss related items, though.

**Comment by megaoka** [comment]
+1

**Comment by emailboxu** [comment]
To add to the X of Y thing, all of the possible permutations (X of Y, Y X, Y's X) are written exactly the same way in Korean, which is why we're doing it for anyone curious. X of Y is the closest "literal" translation but often sounds odd for natural English speakers.

**Comment by megaoka** [comment]
Right. Literal translations are nice, but often do not work out. It's best if you get the concept and adapt it to the language. This is my opinion, of course.

I agree with the Y X instead of Y's X, that makes sense now that you explain it. :+1:

**Comment by emailboxu** [comment]
:+1:
