### ISSUE TITLE
Name translations

### ISSUE THREAD

**Issue by khakiout** [Treeofsavior/EnglishTranslation#396]
Hi, I looked at the wiki and there is a difference between _[Mummyghast](https://github.com/Treeofsavior/EnglishTranslation/wiki/2.4.%20Item)_ and _[Mummy Ghast](https://github.com/Treeofsavior/EnglishTranslation/wiki/2.9.%20Boss%20Monsters)_. Which should we use?

머미가스트     Mummy Ghast
머미가스트 카드  Mummyghast Card

Also in QUEST_100_en.tsv, there are translations having _Tree Ambulo_ VS _Triambulo._

**Comment by emailboxu** [comment]
I think it's Mummyghast. I think the 2 word suggestion for the Wiki was mine, but I'm pretty sure it's intended to be a single word (lowercase g).

**Comment by imcgames** [comment]
We'd like to keep it as single word if it isn't so weird. :smile:

**Comment by khakiout** [comment]
How about Tree Ambulo? Will it be _Treeambulo_ or _Triambulo_?

**Comment by imcgames** [comment]
Treeambulo :smile:
