### ISSUE TITLE
About Item quantities

### ISSUE THREAD

**Issue by vegax87** [Treeofsavior/EnglishTranslation#402]
The current format is "Item Name X ea" but I think it's not very suitable, so we could use a format like this "Small HP Potion x 3", this format is widely used so it would be easier to understand.
What do you think?

**Comment by Sunaries** [comment]
This has already been discussed with @imcgames : https://github.com/Treeofsavior/EnglishTranslation/issues/283 

I personally like the idea of using parentheses to indicate an quantity.

**Comment by vegax87** [comment]
solved
