### ISSUE TITLE
New official forum layout

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#412]
Anyone else kind of unhappy with it?

It's really disorganized and seems to be less of a forum than a page of threads that people can randomly join. For an official forum that will ideally be used for bug reporting and translation discussion I feel like it should be more organized. I put up a post on the forum about using a different forum format, don't know if the idea will stick.

I feel like even Github is more organized as a discussion board than whatever layout imc is are using for their forum..

**Comment by megaoka** [comment]
https://forum.treeofsavior.com/categories

If you click the Categories tab, it is organized. I'm not sure why that's not the default view. I'm just glad this area will be for discussing actual development and translations now-- no more "will ToS be delayed" "issues." :smile:

**Comment by megaoka** [comment]
Side note, interesting that it doesn't use it's own account system. I don't use Facebook or G+, so I'm sort of relegated to Steam which doesn't work.

Guess I'll have to wait.

**Comment by laurencee** [comment]
We shouldn't be raising issues in the english translation github repo that aren't directly related to the repo...
