### ISSUE TITLE
Ellipses (...)

### ISSUE THREAD

**Issue by Chaosbelow** [Treeofsavior/EnglishTranslation#437]
Hi, just starting to edit and I am noticing a lot of ellipses have only two periods instead of the typical three. I am not entirely sure if I should add an additional period. My thought is that its not necessary and will only cause additional and potentially un-needed changes to a lot of translations. The additional period does not add much and looking through most sentences the two periods seems to be fine.

Thoughts?

**Comment by emailboxu** [comment]
The Korean files only have 2 periods which is why most of us leave it as that. I don't think the three dots are necessary tbh.

**Comment by Chaosbelow** [comment]
I figured as much, thanks ! :+1:

**Comment by Nagoda** [comment]
All these ellipses should have three dots in the English files. Two dots might be an accepted standard in Korean writing, but in English an ellipsis is almost always three.

**Comment by ensata** [comment]
There's a third option, which I would recommend. There is actually a Unicode ellipsis (…) that's meant for these things. It might look similar to writing three dots on certain fonts, but it's a single character. You can type it in by pressing Alt+0133.

**Comment by Chaosbelow** [comment]
For now I'd say stick with the two periods for the ellipses. It keeps it cleaner and is just shorter in general, which is good. If there is an issue with the two periods then we can change it later and pretty quickly. I will close this issue soon unless there's any other opinions.
