### ISSUE TITLE
Tree of Savior Story Page

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#438]
I think that needs some editing too, so here's my fix of it. 
#432 is relevant. I believe "The Day of the Divine Tree" is more correct than "The Day of Divine Tree", but it's up to y'all at IMC to decide which is better.

Blessed by Goddess Laima, the capital was a symbol of prosperity. Under the reign of a wise king and with the blessings of the Goddesses, happiness filled the lives of its people.

Goddess Zemyna, goddess of earth, blessed the land with good harvests each year. Goddess Gabija, goddess of fire, taught people how to use fire to warm their homes and cook their food. Goddess Vakarine's star helped travelers navigate their way, and Goddess Ausrine guided souls to rest in peace. The Goddesses were always with their people.

But prayers began to be left unanswered one day. The people thought the Goddesses would return soon and did not take them seriously.. But that may have been a sign of danger.

The Divine Tree suddenly emerged at the center of the capital and ravaged the kingdom. The capital was destroyed before anything could be done and many shed tears for the loss of their loved ones. The people fled but the disaster overtook them.
The sight that greeted the survivors was gruesome. Lush trees and splendid flowers turned into monsters that swallowed people, turning land and forest into a living nightmare. The capital collapsed and its impact was so great that the damage extended to other cities.

The Day of the Divine Tree.
Four years have passed but these words still haunt the people of the kingdom. The monsters are as barbaric and as fierce as ever, and no one knows when the capital will be restored. The Goddesses did not return.
Four years were not enough to heal the wounds of the people inflicted on that terrible day, but everyone has been striving and yearning for their old lives.

One day, in the midst of despair, the people of the kingdom gathered in Klaipeda, claiming that they had dreamed of the Goddess. 
Could this be a sign of the Goddesses' Return? Or is it the beginning of a new disaster? No one knows.

**Comment by imcgames** [comment]
Thank you for your suggestions on edits! :smile:  :+1:

**Comment by Sourpusss** [comment]
Looks good, but there's still a couple things I think should be changed:

Second Paragraph - "taught people how to use fire for to warm their homes," should be "how to use fire to warm."

Third Paragraph - I feel like it should be "The people fled, but disaster overtook them."  The removal of the "the" is optional, but the comma is not.  Maybe add a "whole" to the "monsters that swallowed people" part.  

Fourth Paragraph - Should be "passed, but." Also I feel like The Day of the Divine Tree should be in quotes, as the first sentence is referring to "these words" as if it were quoting them.

**Comment by emailboxu** [comment]
Thanks, fixed the grammatical errors.
