### ISSUE TITLE
Lines missing from Item.tsv

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#446]
I think you broke something, imc, I'm seeing a lot of blank lines in Item.tsv that weren't there before (see lines 11 and 16, for example). 5112+ is completely blank til the end of the document as well.

**Comment by imcgames** [comment]
5112+ are blank because they haven't been translated yet. :sweat_smile: 
(actually, for all files, lines with 20150701 in the line code don't have translations yet)

**Comment by emailboxu** [comment]
Line 11 is ITEM_20150317_000011, though, and it's blank. A few more examples I can see right away are ITEM_20150317_000016 and  ITEM_20150317_000018.

**Comment by imcgames** [comment]
Yup, for blank lines before 5112, those lines were actually there before then removed, but came back again with this update. We're going to work on getting them removed again. :sweat:
