### ISSUE TITLE
N/A lines to be translated or not

### ISSUE THREAD

**Issue by Chaosbelow** [Treeofsavior/EnglishTranslation#449]
Not sure if its just for this particular pull #445 or if its for every file with N/A. But do we translate them or not?

**Comment by imcgames** [comment]
It applies to all files if there is but I don't think we have N/A anywhere other than ETC :wink:

**Comment by Sunaries** [comment]
From what I've read so far, the N/A are strings irrelevant for the player, but rather pertaining to system engines, variables and whatnot. 

EDIT: Ninja'ed by imcgames. :fast_forward:

**Comment by Chaosbelow** [comment]
Alright, thank you!
