### ISSUE TITLE
Missing translations in ITEM.tsv

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#451]
Hello @imcgames,

After checking this pull request https://github.com/Treeofsavior/EnglishTranslation/pull/448 and I'm seeing the changes made to ITEM.tsv. The names in English for these weapons are wrong, but how come they are missing from the current ITEM.tsv?

ITEM_20150317_000011
ITEM_20150317_000016
ITEM_20150317_000018
ITEM_20150317_000032
ITEM_20150317_000033

etc.

They are all missing again, [because I know I've done a lot of names on these equipment](https://github.com/Treeofsavior/EnglishTranslation/wiki/2.3.%20Equipment). There are a lot of blank lines that have been correctly translated in the past in ITEM.tsv. ㅡㅡ;; The descriptions of these weapons are correct and they are thankfully present. I haven't even checked other .tsv files. 

Do you have an explanation for this?

**Comment by imcgames** [comment]
Blank lines in ETC and ITEM dated before 20150701 (in the line code) are lines that were removed previously, but came back again with the latest script update. (you might notice those lines weren't around in the translation files before the latest script update)
But in the end, those lines won't be used so we're going to work on getting them removed.
Sorry for the inconvenience and we'll try to sort it out soon. :cry:
