### ISSUE TITLE
Keywords, Reference File, & Guides

### ISSUE THREAD

**Issue by ensata** [Treeofsavior/EnglishTranslation#458]
https://github.com/ensata/ToS-en-fork/blob/notes/Keyword_notes.tsv - General Glossary of Keywords
https://github.com/ensata/ToS-en-fork/blob/notes/mapnames.tsv - Glossary of Map Names
https://github.com/ensata/ToS-en-fork/blob/notes/Style_Guide.txt - Personal Style Guide
https://github.com/ensata/ToS-en-fork/blob/notes/GitHub_Usage.txt - GitHub Usage Guide

Don't forget that these are not official, but mostly contain guides, notes, and my personal suggestions for translating key words and terminology for the game.

`-original post-`
Since the wiki got a little inconvenient for me, I made my own reference file to make things easier on my side of things. You can see the whole thing on my fork: https://github.com/ensata/ToS-en-fork/blob/notes/Keyword_notes.tsv

I ended up making my own translations for keywords that weren't in the Wiki yet, and I had to record it somewhere for when it had to be replaced - and then I just added useful notes to it.

The Base Attributes aren't in the wiki, and there are several ways to translate it, which I wrote down. There's also the names for the four class categories (not the first class, even though we could make it the same,) and so on. 

Please look over and think about it.

**Comment by megaoka** [comment]
Thanks for this. It was a little inconvenient to browse to each wiki page and CTRL+F for the term.

**Comment by ensata** [comment]
I've added a new file, which is a log of what I've reviewed and translated for accuracy: https://github.com/ensata/ToS-en-fork/blob/notes/Progress_chart.tsv

By the by, the reason I'm sharing this stuff (and the reason I joined the project last week) is not because I'm a fan of the game and want to help, but because I've seen feedback that this translation project is <i>very badly organised</i>, and the translation quality is <i>awful</i>. @imcgames deciding to let the fans translate the game for free is a <i>very</i> risky move, and I wanted to see what was going on.

**Comment by ensata** [comment]
I've now added a Style guide.
https://github.com/ensata/ToS-en-fork/blob/notes/Style_Guide.txt

It's basically just a few notes and reminders for myself, on the basics.

**Comment by ttgmichael** [comment]
Hey ensata,

Thanks for making this. So do we just put our names on the files we want to translate then?

It'd be great if IMC had a spreadsheet log like this that isn't on Github (like on a google doc) so people can just edit their names into and we would all know who is translating what real-time.

**Comment by ensata** [comment]
Well... I didn't really think that far. The log's just a quick checklist I made as a sample. Google Docs will look nicer, but you can see that basic spreadsheets are possible on GitHub, too. Since everyone's a bit rag-tag right now, you should probably just make a personal copy, share it, and hope that someone bothers to look.

For the way I laid it out, you'd make a new column for yourself, add your name and the type of pass at the top, and then start ticking your personal progress. 

It's bare-bones, and I should probably explain it a bit more, but I'm just sharing the way I'm managing myself.

**Comment by imcgames** [comment]
We can try spreadsheet log using google spreadsheet if many of you think it's needed. 
But you'll need to login to edit the spreadsheet to prevent trolls. 

Another way would be to open a issue with tables where you guys indicate which lines you'll work on through comments, and we'll update that issue with your comments every now and then.

**Comment by ttgmichael** [comment]
For now, I think as long as people are marking x's on the lines they editted (not just reviewed), the better sense that we can get about the progress of the English translation. 

Haha, trolls would be a nightmare especially this early on ( the game's not even out yet! D: )

**Comment by ensata** [comment]
Thanks to Hanlon's razor, you usually can't tell the difference between a troll and an idiot, especially on the internet... and, well, I already ran into that nightmare for you, yesterday morning.

Anyway, @imcgames , even though I made my own spreadsheet, I do not suggest a Google spreadsheet right now. It probably won't work. 

I don't know if you've figured it out yet, but I'm familiar with these types of projects. I quickly recognised that doing the translation this way was risky for IMC, and I know about some of the potential problems that occur. Despite what you said on the blog, I actually don't believe that this will bring the international test faster. The _first_ test, maybe... but after that, I'm certain that it will be much slower and unreliable than trying to hire a team or partnering with a western studio, if it's not that bad already.

I've given a lot of free hints so far, but this is where I'm starting to run short. I really don't want to sound forceful about this.

**Comment by ttgmichael** [comment]
Yep, Google spreadsheet idea would just complicate things if there are trolls. 

Technically, all Github projects will have the risks of having merge conflicts when people edit the same lines. The difference is that many Github projects involve a team that strongly communicates with each other and they all know who's coding what. This project lacks that, so the risks aren't minimized. Anyone can just start translating and they will easily end up editing lines that someone else is also editing. Hiring a studio to translate will certainly simplify and hasten the process, but the translation quality will ultimately be similar to our translations. This project is just slower. I actually prefer the slow process as it means IMC has more time refining the game more with each Korean CBT.

If we can finalize these new guidelines, then I believe we are making the right steps towards a more organized project. We can also try speeding things up by assigning files/lines to certain translators (thus IMC will only merge those lines from pull requests of specific translators). This method isn't to look for the best translator to translate key lines, but rather to prevent merge conflicts. Should we do that?

**Comment by ensata** [comment]
I think you missed what I was talking about. Merge conflicts are easy to fix, since you just need to submit smaller packets. (It's also, literally, another issue.)

I put the log up to show my completion progress. An x directly in the file is a start, even if I don't like it, but a summary is also needed, among several other things. A collected summary would be even better.

The final translation quality of this GitHub project is also debatable, since one of the actual problems that will happen in the future is simply getting to that point - We're not being paid for this, so there will always be a looming risk over @imcgames that key people will leave and they'll be stuck with broken English. Hiring a good writer or partnering up must happen, at some point in the future. I don't know what it's worth, but I gave you a few tools to delay that and make this stage a little easier, just for a bit.

It's up to you to believe me or not, but at some point, I'm just going to hope that IMC doesn't screw up their international release, like some other MMOs.

**Comment by ttgmichael** [comment]
Ah, I didn't read your advice to that degree. I very rarely leave things half-baked, so I guess it's a bad habit to assume everyone will contribute until the project is finished; I believe a lot of your points. ^^

For now @imcgames , I think it's important to maintain a good momentum for this translation project. If the project slows down, people's morale will falter and some might start to drop out. Everyone should be writing a summary of files editted and changed in order to keep each other on page of what's happening. Which is why I agree with the new guidelines.

**Comment by emailboxu** [comment]
PS, Day of Divine Tree is the official IMC name for it so you should stick to that. They also refer to the Divine Tree on multiple occasions, so Celestial Tree doesn't make sense.

25 - Tenet Chapel Basement works better here.

31 - Fedimian is correct because of the -안, which is pronounced -an. Generally the word is used prior to an item, so I'm guessing the country is Fedimia and the item is a Fedimian X.

51 - Magical Association probably is what was intended by original choice of words.

55 - Swordsman, not Sword user. Same goes for the other classes, they refer to the generally accepted video game translations used in every other Korean video game involving similar classes. The reason I disagree with your "user" addition is that the classes can use other weapons and are not restricted to Swords. Swordsman usually refers to a melee warrior in general, for example.

68 - Magician

81 - Archer

88 - Hackapell is better here. According to Wikipedia the alternate spellings of the word include "Hackapelit, Hackapelite, Hackapell, Haccapelit, or Haccapelite." 

94 - Cleric

Also if 44 is actually an NPC and not a monster, it's probably Kenburg or something similar. The first syllable is makes a "ken" noise (ㅋ is a hard "k" sound) and the last two make the "bug" noise (no "English" R sound in Korean).

**Comment by ensata** [comment]
Divine and Celestial has a subtle difference in English; both refer to something heavenly in nature, but 'Divine' has a stronger implication that God is directly responsible for it. I'm not actually using Celestial atm, it's just a reminder.

25 - My bad. For some reason I was thinking of hidden passages.

31 - 'Fedimian' with the n is the actual name of the in-game city, and appears that way in dialogue. The 'n' appears to be a clash between Korean grammar rules and English naming systems, which is why I put down 'Fedimia'.

44 - I'm pretty sure it's an NPC. I traced the pre-edit version to a Google translation to 'Cans bug', and someone else edited it to 'Cane Bug'. It took me a long time to research potential names and find a phonetic match: Cyneburg (http://www.behindthename.com/name/cyneburg) (BTW, the original translation for Henryka was "F slow car".)

51 - 'Magical Association' is painfully generic, so I simply picked up a thesaurus and looked for something that didn't exist in another IP. (Mage Association is used in Fate/stay night, Mages Guild is in Skyrim, etc etc)

55, 68, etc - I forgot to add the 계열. The reason I thought of 'Swordfighter' and 'Clergy type' and so on is because of lines that try to talk about the entire class tree, and not a specific class. You can use "Swordsman", "Wizard", etc, but there is a risk that the player will not understand that there are more classes in the game. (see https://github.com/Treeofsavior/EnglishTranslation/commit/4d8d9428f1642efed2b0daf8386aa0e022f36fe3 )

88 - Since this is a Finnish loanword of "hakkapeliitat", none of the spellings are better. The C and K is an English transcription to enforce pronunciation. Neither is better, but Age of Empires uses Hackapell, so I avoided it.

**Comment by ensata** [comment]
Issue's now obsolete, and closed.
