### ISSUE TITLE
Naming convention for Mines?

### ISSUE THREAD

**Issue by DrBillygoat** [Treeofsavior/EnglishTranslation#493]
On the wiki they have The Crystal Mines, but in ECT.tsv files they have some unmentioned mines translated as 
제2 채굴구역 - Mining Area 2
고갈 1 구역 - Exhaustion Area 1
and 지반 붕괴 구역 - Ground Failure Area

As I just started helping with the project I'm not really sure how much liberty to take with naming and changes, as sometimes I'm not sure if i'm looking at a "Good enough" translation or a "Finished" one.  It feels weird and slightly boring to refer to mines by "areas" rather than Zones, Sites or even sectors.  Should I just leave them as is or do what I was thinking which was along the lines of

"Mining Zone 2" 
"Exhausted Site 1"
3rd one I'm not so certain, I think it's a cave in zone just based on it's proximity to the other mining areas in the file.  But something like "Cave in Area"?

**Comment by imcgames** [comment]
Well, using "Area" has its advantage of being convenient and consistent in game :smile: 
But if it isn't in the wiki and the community really feels that it has to be changed, we are open to having it changed too. (but let's not use "Zone" since it's a term used in the game)
