### ISSUE TITLE
Understanding file structure

### ISSUE THREAD

**Issue by diteix** [Treeofsavior/EnglishTranslation#496]
@imcgames could you please explain why there are lines in file QUEST_JOBSTEP.tsv that are identical like, for example, line QUEST_JOBSTEP_20150317_000003 and QUEST_JOBSTEP_20150714_002600.
This last one you modified yesterday, I should modify the first for them to be equals?

**Comment by imcgames** [comment]
For the line you mentioned, the Korean text was edited a bit so they are not actually identical in Korean but they do mean the same when translated soit is ok to make them equal though not required. 

(this is for the case of QUEST_JOBSTEP_20150317_000003, QUEST_JOBSTEP_20150714_002600. and though there area many similar cases, there also may be some lines with different meaning after the small edits)
