### ISSUE TITLE
Re: Polite lines...

### ISSUE THREAD

**Issue by ttgmichael** [Treeofsavior/EnglishTranslation#499]
Attempting to translate more lines in ETC.tsv.

Just wanted to ask people and @imcgames what's your opinion of how to translate lines that are 'polite'.
For instance, some of the boss fight lines, the direct translation would be "Please defeat [boss]". Is the "Please" necessary?

This is understandably a Korean/Japanese kinda thing (for software I guess?) that they use verbs in their polite form rather than direct commands (as if the game is telling you to DO THIS). But in English, not every command starts with a "please" xD (at least I'm more in favor of a straightforward script). Who prefers "Defeat [Boss]" vs "Please defeat [boss]"?

**Comment by vegax87** [comment]
I agree, it's very unusual to read "Please defeat [Boss]" because it could be a quest description and not a dialogue
Anyway, I prefer the modern version "Defeat [Boss]" :)

**Comment by Nagoda** [comment]
I noticed this a while ago and I thought I made a post about it, but I can't find it.

I agree that all of these "please X" lines should be changed to just be direct commands (i.e., "Please defeat BossX" becomes "Defeat BossX"). This seems like a translation issue, where the literal Korean translation ends up sounding too awkward and formal.

The game's quest tracker UI or pop-up text giving instructions (stuff in the ETC file) should never say "please". Spoken character dialog in the QUEST files, where an NPC might reasonably use the word "please" when addressing the player character is mostly fine. Still, there's probably a lot of overly polite language and "please" usage that could be cleaned out of the QUEST files where appropriate.

**Comment by imcgames** [comment]
Yup, sounds like a valid point to remove the "Please" unless it's a request from some other NPC in the game.

**Comment by froodybanana** [comment]
If nothing else it will be much easier to determine when the international version becomes available for testing, and we get some more context on the lines.
