### ISSUE TITLE
Is the wiki still incomplete?

### ISSUE THREAD

**Issue by DrBillygoat** [Treeofsavior/EnglishTranslation#505]
In Ect.tsv there's a lot of files translated as "[Some name listed under Sub-area] Vacant Lot" but I came across one where the translator just wrote "Vacant Lot" and ignored the 사슴발굽.  It seems to translate as Deer Hoof (at least according to online translation) but I'm inclined to say there's no area by that name as it sounds nothing like other areas. It also seems like there were others not listed on the wiki, but given names in the file (Each one was followed by "공터" for "Vacant Lot"):
쥘루티 - Juility
지비라 - Zivira
앳스팔비 - Atspalbi
발디티 - Valdyti
비레티 - Byreti

Are these just names temporarily given by the translators while IMC decides what to officially call it? Things they haven't reached yet?  Mistakes made by people using online translators when in reality it's all part of one long name? Or are things being added as they're found and there's actually some specific place to bring them up that I haven't discovered?

And while I have this open anyways maybe someone could give me their opinion on how "Juility Vacant Lot" sounds and how you think it would be used.  Since there are so many (15 Vacant lots in Ect.tsv, all seemly located in their specified area) it sounds like a space for....player housing maybe?  Or player-driven stalls?  If one is located in Juility it seems redundant to even include the name of the area instead of just flat out naming all of them "Vacant Lot"

**Comment by ttgmichael** [comment]
Although I didn't translate those lines, I'm incline to say that those "location" names are temporarily given. Personally, I think that it's still quite the leap that "Juility Vacant Lot" could mean player housing (IMC hasn't indicated anything about that), but it might be for people to place their stalls I guess. It wouldn't be redundant if the game requires a designated name for each of those areas. ^^

**Comment by DrBillygoat** [comment]
Good point.  I'll just leave as-is for now until we can get some context.
