### ISSUE TITLE
How do you know if your line is too long and you need a line break?

### ISSUE THREAD

**Issue by vtange** [Treeofsavior/EnglishTranslation#511]
Do you follow a word-count rule or character count-rule? Does the game not do line breaks automatically?

I could play safe by keeping things short and using multiple breaks, but that might limit the amount of detail I can put in a sentence/ make things pretty awkward.

**Comment by imcgames** [comment]
For dialogues, it should be kept shorter than this.  :smile: 

![box](https://cloud.githubusercontent.com/assets/11382705/8770365/2cfaf1cc-2eeb-11e5-9f61-df1794f03c8f.png)

**Comment by ensata** [comment]
Just to clarify for imcgames, that is roughly 100 characters of text, and/or 1 single average-length English sentence of 15-20 words.

In other words — if in doubt, write only one sentence per line.
