### ISSUE TITLE
Quest_JOBSTEP Problem.

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#516]
I was translating some lines and found two that are translated into basically the same thing.

Line-2882 translates to "Meet the master sorcerer in the forest of origin"

Line-2876 translates to "Go find a master sorcerer in the forest of origin"

Is this how its suppose to be or am i doing something wrong?

-Ghqst

**Comment by Flevalt** [comment]
There are several of these pairs with almost identical translations. There always seems to be a single word that makes the difference between such a pair. 

While I'm not sure what difference the word is supposed to create between them, as far as I've seen from already translated pairs, all of these pair lines have been translated identically so far.
Hence I'd leave them identical.

**Comment by Kxizen** [comment]
Okay. thanks for the reply man.
