### ISSUE TITLE
Unclear translated line QUEST.tsv

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#520]
Line 2118 says "Please... save us from this horrible contract...{nl}Remove... from the contract of the declaration..."

Its unclear.. Remove what from the contract? is it remove us? remove it? This should be fixed for clarity.

**Comment by imcgames** [comment]
Something like... they're bound to this horrible contract which is causing them to suffer.  :sweat_drops:

**Comment by Kxizen** [comment]
Ok ill add something in.
