### ISSUE TITLE
How do {nl}'s work? + {nl} at the end of lines

### ISSUE THREAD

**Issue by vtange** [Treeofsavior/EnglishTranslation#526]
Hi, I spent a good chunk of last night reviewing the first 700 lines of QUEST.tsv and adding {nl}'s where I feel the line went too long without one, I put them mostly at the end of sentences and phrases. 

There were a LOT of {nl}'s though, at the end of lines. I left them alone since I thought the game might need them to set up for a line that comes after said line. For example:

"Line 1 Line 1 Line 1 Line 1 Line 1" {nl} -> Line 1 moves up for Line 2 to show up.

Is this how things are supposed to work? Or am I just being too careful and the {nl}s at the end of lines aren't needed?

**Comment by imcgames** [comment]
{nl} 's starts the translations on a new line. Some lines may be used together in one dialogue box so it'd be safer to leave the {nl} 's at the end of the lines if the Korean (original) text has it.
