### ISSUE TITLE
One revelator or many revelators?

### ISSUE THREAD

**Issue by froodybanana** [Treeofsavior/EnglishTranslation#527]
Is the player "a" revelator, or "the" revelator? The quest dialogue seems to indicate that there are many revelators, which makes sense since there are many players, but everyone refers to the player as "the" revelator, as if the player is the only one.

Can anyone with knowledge of the story clarify?

**Comment by vtange** [comment]
I've also encountered this problem. For now, I'm leaving things as they are; sometimes it sounds like the player is treated as just another Revelator out of many, other times the NPC treats the player as a special/unique character compared to others. Maybe some NPCs can pick out special players?. We will never know until we play the game.

**Comment by imcgames** [comment]
Player is one of the many revelators who is on the quest to become THE revelator hehe :wink:

**Comment by froodybanana** [comment]
Ah that does make sense. Now the question is just how to get the dialogues to reflect this. Hm...
