### ISSUE TITLE
Epitaph...

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#532]
There is a line that reads - "I leave this epitaph.{nl}I will take my pride as the greatest thief and issue a challenge to the strongest magician"

Would it be best to change the word "epitaph" to something else. Something easier to understand. I had to google that word lmao. What do you think i can use to replace it?

**Comment by froodybanana** [comment]
I'm assuming this is the part in question:

QUEST_20150317_000161   Unnamed Thief's Gravestone
QUEST_20150317_000162   I leave this epitaph.{nl}I will take my pride as the greatest thief and issue a challenge to the strongest magician. 
QUEST_20150317_000163   Can I say that I was successful by just stealing?{nl}I guess I can say I was successful by stealing from the greatest magician.{nl} 
QUEST_20150317_000164   But, I am not.{nl}I want to be the greatest thief of all time, not just the greatest thief of this time. 
QUEST_20150317_000165   Finally, I found a way to enter Magicians' Tower.{nl}That is to concentrate all the magical power to a specific place.{nl}Now, I just need to take a decisive step. 
QUEST_20150317_000166   Soon, my special device will be activated.{nl}If you do what I do, you will also be able to enter Magicians' Tower.{nl} 
QUEST_20150317_000167   Of course, after that, you should show those dumb magicians what it's like to be outsmarted! {nl}Haha!

In this context epitaph would be the correct word. An epitaph is a message left on a gravestone or a plaque in honor of the deceased. An obituary typically draws the mind towards an article in a newspaper or magazine, and a commemoration is more of a speech type deal. An inscription is a more general term, and doesn't really underline the fact the person is dead and the message is about him.

**Comment by Kxizen** [comment]
You're right. Just was wondering if there was an easier term.
