### ISSUE TITLE
Corrected lines.

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#534]
Hello,

Would it be fine if i read all of the lines and placed an "x" in front of the ones that are ready to go?

**Comment by ttgmichael** [comment]
Not sure what you mean, but I'll say, put an x on the lines you edit. not the ones you read. Otherwise, there might be confusion on which lines have been proofread and which haven't.

**Comment by Kxizen** [comment]
thats what i meant. I want to read the lines and ones that can go into the game i will place an x at the beginning indicating that its already been proofed.

**Comment by TOSBase** [comment]
I think it kinda makes more sense to add an X to lines you proofread instead of lines you translate because they are supposed mark lines that are fine and if everyone just marks his own lines as ok this might cause problems so I don't see why it shouldn't be ok to mark proofread lines with an X.

**Comment by Kxizen** [comment]
Great. ill start proof reading then thanks!
