### ISSUE TITLE
Preventing merge conflicts

### ISSUE THREAD

**Issue by ensata** [Treeofsavior/EnglishTranslation#536]
I am way too tired for this. Here are some rules to follow in your editing to prevent merge conflicts, and make it easier to follow.
1. Edit lines in groups. For example, edit a chunk of 100 lines, from 1-100, or 101-200, etc.
2. Write down the chunk you reviewed in the commit summary.
3. _Do not edit more than 300 lines in a file in a single commit/pull request._ GitHub will not generate a diff and you will need to use the command line or dig into the commit history to track problems.

I am adding this to my style guide, which I doubt anyone will read. Please add at least point 3 to the Wiki, and start telling people to read the damn thing.

**Comment by imcgames** [comment]
Yup, agreed.
If you have more suggestions, share it with us here: https://github.com/Treeofsavior/EnglishTranslation/issues/540

**Comment by vtange** [comment]
if you guys need an example, I've been doing it like:
[FILENAME] ### - ### rev# + details + any broad changes like the doppelsoldner fix
