### ISSUE TITLE
Please select a cheat start group? uhhh..

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#551]
"QUEST_20150317_000007  Please select a cheat start group
Is this correct? @imcgames cheat start group? explain to me what this is so i can make the sentence a little easier for everyone.

**Comment by imcgames** [comment]
That's actually what it really says :laughing: 
It's a system message so no need to make it easier for everyone.

**Comment by Kxizen** [comment]
Ok thanks.
