### ISSUE TITLE
Apostrophes

### ISSUE THREAD

**Issue by Flevalt** [Treeofsavior/EnglishTranslation#553]
Since I got a false recommendation in my last pull request and am not sure how many people don't know about the proper usage of apostrophes('), I'll just explain a bit on them here. 

This is just for people who are unsure of how or when to use apostrophes.
The most common cases in which you use an apostrophe in English are as follows:
1. To show possession
   
   1.1 Of singular words (Example: A friend's dog.)
   1.2 Of nouns ending with s (Singular Example: The Goddess' statue | Plural Example: The Goddesses' statue)
2. For abbreviations (Examples: don't, can't, it's, shouldn't) 

You do not use an apostrophe to:
Build a plural (False: These two Monster's) | (Correct: These two Monsters)

Hope it helps some.

**Comment by froodybanana** [comment]
Miner's Village (one miner who has a village)
Miners' Village (many miners who have a village)

This one happens quite a bit all over the place.

**Comment by megaoka** [comment]
:+1: 

I'd like to add that you do not use "it's" for possession, just "its."

e.g. - "Its dog" not "it's dog"
