### ISSUE TITLE
Capitalization of titles?

### ISSUE THREAD

**Issue by Flevalt** [Treeofsavior/EnglishTranslation#555]
I encounter it pretty often that people are called by their title.
Sometimes it are military ranks, other times it's their job title.

The titles are usually not capitalized whereas the names are.
But when their titles are used in conjunction, as part of their names, shouldn't the titles also be capitalized?

Examples: 

> Commander Vacenin
> Thief Hubertas
> Monarch Bloot
> Baron Areluno
> Baron Secretary Venius
> Guard Gofden
> Cryomancer Costas
> Tenant Charlotte
> Farmer Daasi

It's especially confusing when looking at monster names. When looking at something like:

> orange Lizard Men

It's hard to say what the monster name is. Are it Orange Lizard Men? Or is the orange just a distinction from other Lizard Man monsters? Since "orange" is used quite often in front of monster names. It speaks against it being part of the monster names. 
But if that's the case, why are they all orange? Shouldn't there be some other colors too? If there's only 1 color there is no point in distinguishing them after all.
Further examples:

> orange Shakmolis
> orange Dandells
> orange Tamas

**Comment by ttgmichael** [comment]
Yes, I think they should be capitalized as they are names. An example of colors being capitalized as they are part of the title would be like the Red Baron or the Black Pearl. ^^

**Comment by vtange** [comment]
For all of the lines I've covered, I've stuck with a full capitalization scheme, even for objects.

random examples (not necessarily ToS related)

people:
Captain Daniel
Red Baron
Limon, Leader of the Knights of Orange
Cryomancer Arnold 

creatures:
Big Hairy Lizard
Elite High Orc
The Gleam Eyes

objects
The Diary of a Wimpy Kid
Fragment of Time

I'd imagine these names are the names we'd see when we approach said NPC, creature, object in the game world. I find it most appropriate to see their names properly capitalized.

**Comment by emailboxu** [comment]
Yes. Capitalize titles, item names (use title-capitalization rules), and monster names.
