### ISSUE TITLE
List of those who qualify for the Beta Keys!!

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#559]
You may check the list of those who qualify for the Beta Keys HERE :

PLEASE MAKE SURE YOU AUTHENTICATE AND LINK your Github ID to the official website’s account. If the accounts are not linked by July 30, you WILL NOT be able to receive the Beta Keys.

Jasdemi
Sunaries
vegax87
emailboxu
megaoka
ArkKnight
dlam
mickeyjulian
ensata
lovelyjh
vtange
TOSBase
ttgmichael
Sourpusss
Saklas
ruru1
khakiout
Flevalt
xapher19
MasterCyria
bonospeak
Chaosbelow
TheStargrazer
hasenbanck
Waterfighter
Pomez
ceddc
Azumii
diteix
Wolvaroo
alastaire61
TendrilTender
MarkofKain
Trepoleth
pixelmonkk
Nagoda
Clariche
xMiiNTY
thefoster9
mtnielsen
DrBillygoat

Thank you.!!

**Comment by ceddc** [comment]
:+1:  YAY !  :+1:

**Comment by vegax87** [comment]
I'm honored :)

Thank you IMC!

**Comment by mickeyjulian** [comment]
Thanks IMC!!! :)

**Comment by Azumii** [comment]
Thank you!~

**Comment by Spl3en** [comment]
Wow, what a nice move from IMC to award the contributors by giving them a beta access !
:clap: :clap:

**Comment by vegax87** [comment]
The official website is under heavy traffic because a lot of people want to join English beta

**Comment by Spl3en** [comment]
@vegax87 Yes, that was predictable. I guess it will continue for a day or two. I feel excited by the hype!

**Comment by arkan0** [comment]
:( ow damm where is my name :'(

**Comment by Azumii** [comment]
The situation will be better after some days yes, can't wait to see you IG
-if we encounter-!

2015-07-27 15:00 GMT+02:00 Cyril Moreau notifications@github.com:

**Comment by hasenbanck** [comment]
Cool, time to link my accounts then.

**Comment by Spl3en** [comment]
@arkan0 Don't feel sad, there's still a chance :+1: 
@Azumii We will encounter Inch'Allah :) I feel so excited just by picturing everybody here playing together to ToS :D It's going to be awesome !

**Comment by arkan0** [comment]
@Spl3en - :D ow god, just waiting _-_ and see you soon at Klaipeda _-_

**Comment by Sunaries** [comment]
Thank you very much @imcgames - I will continue to work hard. 
Will the real time translation tool be present in this beta?

**Comment by ThanhKhoa** [comment]
I want code :)

**Comment by Loztchild** [comment]
I don't get it how do you get the Github ID?

**Comment by ThanhKhoa** [comment]
ID : https://github.com/ThanhKhoa

**Comment by diteix** [comment]
WOW thanks @imcgames !!!!
Right now I'm having issues on ToS website, but how can I link my github account to my profile account?

**Comment by Spl3en** [comment]
@diteix Go to www.treeofsavior.com, log in using your Facebook / Google+ account (be patient), wait for your account to be loaded (again, be patient, it can takes few minutes with the current traffic overload), then click on the Github logo at the right top corner of your screen.
![Github Tos](https://i.imgur.com/cVLGL5j.png)

**Comment by Loztchild** [comment]
Thank you and I'll shall wait

**Comment by Gardosen** [comment]
Hey @imcgames can you please forward me an email address of yours that we can get in touch about the contrubutors of our web translator?

i am trying to contact malikim over the forum, but because of all the fake account spammers, the forum is totally overloaded.
would also be nice if you could get rid of these people. otherwise you will see many dissapointed people because they got no account, and many resellers who will sell the accounts on ebay or elsewhere. i saw the same happening for Heroes of the Storm, and it hurt the community strongly.

**Comment by diteix** [comment]
Thank you guys, I'll be patient.

**Comment by Loztchild** [comment]
@Spl3en I click the button then i accept the share my information not sure if i did it correctly because I try doing it again and it gives me a blank page.

**Comment by Spl3en** [comment]
@Loztchild If you want to make sure you've linked your Github account with your IMC one, go to your Github account Settings (top right corner of this page, click your profile icon, settings), in Personal Settings menu on the left, click "Security" : 
![Security Github](https://i.imgur.com/gGIktyG.png)
You'll see a "Security History" appearing, with a list of entries. Look for "oauth_access.create - imcgames" entry; if it is present, you've correctly linked your Github account.
![Linked](http://i.cubeupload.com/wo0gZv.png)

**Comment by Loztchild** [comment]
Ok thank you @Spl3en for the step by step tutorial XD and I see it there.

**Comment by diteix** [comment]
@Spl3en I thank you too. Helped me a lot.

**Comment by Inperatrix** [comment]
How often is this name list updated?

**Comment by Spl3en** [comment]
@Inperatrix According to @Sourpusss, those who edited at least 100 lines get their key for the CBT.

**Comment by diteix** [comment]
@Inperatrix 
"If you have contributed at least 100 lines by July 26, you will receive 3 Beta Keys via email regardless of your selection as Tester in the Official Website."

https://github.com/Treeofsavior/EnglishTranslation

**Comment by megaoka** [comment]
Thanks @imcgames, this will be incredibly helpful for us. :smile:

Will the Real-Time Translation Tool be available for use?

**Comment by Chaosbelow** [comment]
Yes! Thank you so much @imcgames !! Thank you for listening to my suggestion in the offical forums ^^

I hope the OTC will be in the game so I can help edit more lines!

**Comment by diteix** [comment]
@Spl3en I already have checked my github and it has the auth to imc, but on Tos site, the icon of github doesn't have my name like in your print. Is it ok?

**Comment by froodybanana** [comment]
I don't think anything on the website is working as intended right now. Best let the beta rush calm down a bit before trying to link accounts. As for me, I can't even get the website to load right now. :)

**Comment by Spl3en** [comment]
@diteix No, that doesn't seem normal. Have you tried to click on the Github icon again on the ToS home page ? Have you still a blank page ? 
Anyway, I wouldn't be too much worried : imcgames have the access they requested, you've done everything possible on your side

**Comment by megaoka** [comment]
@mtnielsen Yeah same here. 504s all over the place. 
@diteix If you're having troubles registering, just hold off for a bit! The site seems to be under quite a bit of stress right now.

**Comment by diteix** [comment]
![image](https://cloud.githubusercontent.com/assets/13291018/8912804/7e44c67c-346b-11e5-9679-d5098e894f8a.png)

@Spl3en I keep getting this after waiting a lot. Better to calm down my hype and wait. =/

Really looking for OTC to help more on translate.

**Comment by Loztchild** [comment]
What I don't approve is people spamming more than one account to sell or give out keys if they get choosing to participate in the beta for their guilmates,friends,family members,etc.It's good and all but some of us would like to get the chance to test or contribute in any way for the actual release.This result in crashing the website...sigh

**Comment by Spl3en** [comment]
@diteix I suggest you to wait for a bit and retry when the website is functional again :) Then everything should be fine, I'm sure! 
If it still doesn't, contact IMC and let them know about your error. ("Error Occureed 49")

@Loztchild : We don't know what's happening, let's not be negative. Reastically, I don't think the forum website has been designed to handle a lot of traffic (the forum was very laggy the first day before they made adjustments), so I bet they didn't want to pay a very expensive website just to handle all the people coming the first day right after the facebook announcement. Everything is going to calm down whenever everybody is registred.
I don't say nobody is spamming the account register, but I don't think this is the reason why the website is crashing.

**Comment by kyesse** [comment]
that's great!
i'm hoping to be one of the testers!

**Comment by HimuroRitsu** [comment]
Congratulations guys! You all deserved it after such hard work contributing to the English Translation. :) Too bad I was unable to contribute as I still have a hard time understanding GitHub...

**Comment by vtange** [comment]
Wow, I did not expect this. Thanks!

**Comment by Gardosen** [comment]
thats the point vtange. you did this without expecting something. exactly those people deserve a key.

gratz ^^

**Comment by Jasdemi** [comment]
Sweet, thank you! :)

**Comment by Kxizen** [comment]
Wait so does that mean.. once you contributed you get 1 key, but those who contributed more than 100 get 3? or must you have contributed 100 times for keys? @imcgames Gonna need that key fam.

**Comment by laurencee** [comment]
Very nicely done, always approve of giving things to those who have contributed. :+1:

**Comment by Pomez** [comment]
Wow totally didn't expect this since I couldn't contribute much ;_;, thank you so much imcgames :+1: . Hopefully the real-time translating tool will be available for easily editing those quest lines :smile:

**Comment by mickeyjulian** [comment]
Reminder fellow contributors you need to link the github account to your TOS Website account or else the three keys would be wasted.

**Comment by Gardosen** [comment]
@Kxizen based on what they wrote you only get 3 keys if you translated 100 lines. which is the list for, it represents everyone who qualified for these 3 keys.

**Comment by Chaosbelow** [comment]
I think my account got auto-linked like 25 days ago? I see both the "oauth_access.create - imcgames" and my GitHub username in the top right corner of the ToS homepage. Doesn't allow me to click the GitHub icon. 

Sorry for being paranoid but I am good to go right?

**Comment by onailime29** [comment]
I need key! Please!

**Comment by mickeyjulian** [comment]
@Chaosbelow Yes it seems that you are all set. :+1:

**Comment by ghost** [comment]
oh thank you :dancer:

**Comment by magcathe** [comment]
Hi, Nialcen and I made a lot of french translations, we linked our accounts on the official site, but it's still written "0 contribution", and we don't appear in the list for the beta keys. I don't see how to solve this problem... If someone of the staff can see my post, and check it, it would be really nice, thank you.

**Comment by ceddc** [comment]
@magcathe This is only for Korean to English translation, made on this Github repository to translate as much as possible of the game for the international beta.

There is at the moment no official IMC project about translating it to other language, but only fan project not related with IMC.

Edit: For below, it's not counted because there is no contribution on github.

**Comment by mickeyjulian** [comment]
It only applies to those who translated Korean to English. The other languages are not supported yet thats why they didnt counted yet your contribution.

**Comment by magcathe** [comment]
ah ok... so what we did was useless for the key AND the translations too (more than 1000 lines...). 

I hope at least, we will have more than 1 key as a fansite, because we are 2 admins to work on it, since one year.

Thank you for the answer

**Comment by Spl3en** [comment]
@magcathe I don't see any commit on your account, where is your repository ? If you want to show your work, you should upload your commits to GitHub and make them public :)

**Comment by magcathe** [comment]
it's Nialcen who created it

**Comment by Spl3en** [comment]
@magcathe https://github.com/Nialcen No commit here too ... How IMC is supposed to know you contributed ?

**Comment by ceddc** [comment]
@magcathe No commit even on his fork also. https://github.com/Nialcen
But that's not the problem,  Just wait for the fansite e-mail on 31 ! :smile_cat:

**Comment by magcathe** [comment]
It's the first time I use github, so it's not easy to understand how it works. 

I see that (I'm not sure you can have access) : 
https://github.com/Nialcen/EnglishTranslation/blob/patch-1/ToFrench%20Quest
or
https://github.com/Nialcen/EnglishTranslation/tree/patch-1

Anyways, I will just wait for the fansite. Thank you.

**Comment by hasenbanck** [comment]
@magcathe I think your work might be useless in the long run. The translations already changed a great deal and imcgames clearly stated that they right now only focus on the English translation.

For the future you need to pay special attention to work with the upstream / origin source to get your work approved / merged. Right now its not the right time to work on translations beside English. 

Good luck on the fansite keys.

**Comment by pixelmonkk** [comment]
thank you so much IMC ! :)

**Comment by magcathe** [comment]
as there was at the beggining folders both in korean and english, I thought we could use what was already done in english to translate it in our language (even if the priority was to translate the korean left in english, for those who could). It was not really clear (to me), but it's ok now... 

I hope I will be lucky next, thank you for the good luck, you too

**Comment by 0ojookinzo0** [comment]
@Spl3en i have linked my acc but after that..i don't know what the @#$#@$...I DELETED MY GITHUB (why did i do that for!? ="=)) and now my acc from Treeofsavior.com still linkin with the old github that i deleted yesterday...is there anyway that i can fix this...can i link it to a new github? (this one: 0ojookinz0o)

**Comment by eskorpion100** [comment]
it remains one kay, pains me . plis ^^

**Comment by PCPrincess** [comment]
If any one of my fellow GitHubians ends up with an extra key and I'm not lucky on 'draw' day, I'd be most ecstatic! 
Of course, I always repay my debts; maybe some crafted potions(or other item) once TOS is released?  /wink

**Comment by KoisHub** [comment]
If you're looking for a Frenchy, here I am ! This is going to be great !

**Comment by Spl3en** [comment]
@0ojookinz0o : You should try to contact a ToS admin in that case, I don't see any way to unlink a deleted account. Well, maybe you should wait to do it, with the incoming beta they must be busy and anyway it doesn't really matter to link your github ID if you aren't in the list.

**Comment by 0ojookinzo0** [comment]
@Spl3en oh i see...thank you so much sir...^  ^

**Comment by ivkanian** [comment]
someome have a key for me?

**Comment by Xilmmar** [comment]
Is there a chance people like me from the Philippines can get a beta key?

**Comment by ghost** [comment]
@Xilmmar just login in ToS site and try your luck, after all it's international CBT. They said though that regions with other publishers don't opt in.

**Comment by Xilmmar** [comment]
Already have.
I'm so excited! :D
If I don't get into Closed Beta then I'll just have to wait for Open Beta.
But thanks for giving so many of us a small chance for our patience. Thank
you again! :D

**Comment by mickeyjulian** [comment]
@Xilmmar Yes because I'm also from the Philippines and I also qualified as one of the contributors for the translation project.

**Comment by Clariche** [comment]
I feel so grateful that I am included in the list, but I also feel quite guilty cause I could not help out much these days. I'll get back to translating more lines soon! Linked my GitHub account and think I'm good to go, so excited for this. Thank you very much ToS team!

**Comment by emailboxu** [comment]
Wait am I too late?!  IMC games please respond! T_T I was away from the Internet for the last few days...

**Comment by Chaosbelow** [comment]
@emailboxu Go link your GitHub account to your account on the main website. You should be good to go. If anything you can open up an issue or send STAFF_Makirim a message on the forums.

**Comment by emailboxu** [comment]
I PM'd the official IMC account on the main forums, because the announcement says you had to link your account by 12 AM on July 30th, EST and I linked it at 12:13 AM EST... @imcgames

**Comment by Chaosbelow** [comment]
@emailboxu I have never messaged the offical IMC account, I am not sure if anyone logs into that. I messaged STAFF_Marikim the other day about an issue and he/she answered immediately. Go ahead and open an issue on the GitHub with their name and then close it out once they answer. I was told that if I didn't recieve an answer by the 31st then to message again. So you should be good. Worse comes to worse there will be a beta key from one of the GitHubbers. I may be able to spare one!

**Comment by emailboxu** [comment]
Thanks, I'll put up an issue on GitHub if they don't respond by tomorrow.  I'm pretty sure imc isn't going to leave me high and dry, but thanks a lot for the offer!

**Comment by TheStargrazer** [comment]
@imcgames  If we link our Github account now are we too late? I was only able to do it now because of timezone differences.

**Comment by ceddc** [comment]
damn, should have done that yesterday. But too much work :-(

People in the list who have not posted here. No guarantee something can be done now  :

EDIT : No requirement to post here, but without mail notification some people could have missed this issue/post if they were like on vacation and stuff.

Ping
@ArkKnight
@dlam
@ensata
@lovelyjh
@ttgmichael
@Sourpusss
@Saklas
@ruru1
@khakiout
@Flevalt
@xapher19
@MasterCyria
@Waterfighter
@Wolvaroo
@TendrilTender
@MarkofKain
@Trepoleth
@Nagoda
@xMiiNTY
@thefoster9
@DrBillygoat

**Comment by MasterCyria** [comment]
Balls. I forgot all about this. If nothing can be done, I understand :) I just got mine linked, if that's of any use :(

**Comment by dustin-dev-throwaway** [comment]
Oh crap, didn't realize we had to post here! I linked my github account a couple days ago =[

**Comment by dlam** [comment]
Oh crap, didn't realize we had to post here! I linked my github a couple days ago =[

**Comment by ttgmichael** [comment]
I don't remember if there was a requirement for posting on this issue thread. My account is linked.

**Comment by TendrilTender** [comment]
I don't remember anything about having to post here, having the accounts linked should be enough.

**Comment by ceddc** [comment]
Hello,

This is not a requirement to post here, the only one is to link the github
account.
But it seems some people have not seen there was a post here, and have
maybe not linked their github account (I guess like vacation and stuff), so
a mail notification can help ! :-)

2015-07-30 9:03 GMT+02:00 ttgmichael notifications@github.com:

**Comment by ttgmichael** [comment]
Haha, some of us contributors like to lurk. Thanks for checking up though @ceddc xD

**Comment by khakiout** [comment]
@ceddc thanks for the notification! I really didn't expect this! :+1: 

@imcgames i just registered/linked my account an hour ago. (3:17 AM EST) I hope I can still have the beta key :worried:

**Comment by Wolvaroo** [comment]
I'm was just lurking this comment, but thanks for the notification anyway <3

**Comment by xapher19** [comment]
Oh wow that's awesome, I didn't expect to get anything :D

**Comment by Saklas** [comment]
Thanks for the heads up, I've already linked my accounts. Let's see if we qualify even without the 100 lines requirement :)

**Comment by mickeyjulian** [comment]
Any of my fellow contributors got their keys yet???

**Comment by ceddc** [comment]
not at the moment.

It's only 13.21 in korea :-)

2015-07-31 6:07 GMT+02:00 Julian notifications@github.com:

**Comment by Xilmmar** [comment]
Has anyone made the same mistake as me?
Gosh I feel so stupid, I signed up here without properly reading the instructions and it turns out this is only for contributors.
I hope this doesn't ruin my chances. T_T
Sorry again for this mistake!

**Comment by amarx3** [comment]
give me beta key pls

**Comment by ivkanian** [comment]
any have a key for me? D:

**Comment by chewny** [comment]
id love a key please..

**Comment by mickeyjulian** [comment]
I think we have more work to do on SKILLS and UI guys...  it's just been updated.

**Comment by MrMoua** [comment]
I thought that if we login on the main website by the 30th that 5,00 people will get a key? Am I wrong ? :o

**Comment by vtange** [comment]
Just to clear things up for you guys, I've no keys yet. Even though my account was linked before this whole announcement. 

But no rush. I can clearly tell their servers are being strained from all the traffic.

**Comment by chewny** [comment]
I was also linked days before deadline. Must be lagging.

**Comment by Saklas** [comment]
via fb just a couple of minutes ago:
*Github contributors, fansite managers, and media will be contacted separately via email within the day.

**Comment by MrMoua** [comment]
:( didn't get a key.. If anyone has an extra beta key please pm me!! I didn't get one.. So sad x'(

**Comment by ghost** [comment]
I'm in the list and keys still not there

**Comment by MrMoua** [comment]
Damn... :[[[[

**Comment by Chaosbelow** [comment]
Got my keys, thanks IMC! You will have your keys by the end of the day. They said it could take up to 5 hours due to all the emails they need to send.

**Comment by ivkanian** [comment]
D: i didn´t get u.u any have a extra key? please pm

**Comment by Chaosbelow** [comment]
@imcgames Quick question, do we need to use one of the keys we received on ourselves if we want to join? Or can we send all 3 keys to different people? Otherwise I only have two keys for others since I'm using one for myself.

**Comment by MrMoua** [comment]
Same.. I didn't get neither... If anyone has extra key pm me! :P I also heard that Github people will mostly likely have extra keys. I don't know though. :S

**Comment by emailboxu** [comment]
You're not on the list @MrMoua, the triple keys were for people who contributed more than 100 lines to the translation project before the 24th of July.

@Chaosbelow Yes you have to register your key on Steam, the other two can be given away and claimed similarly.

**Comment by ceddc** [comment]
@Chaosbelow you need to use one. So two keys to give to friends.
"Maybe" you can get selected by account on website, you will get another mail with another key.

**Comment by Chaosbelow** [comment]
@ceddc I figured as much after looking at the email but thought maybe it was different. Was hoping I'd be selected in but it seems not. Not a big deal, I'll use one for myself and two for others.

**Comment by ghost** [comment]
did already all ppl from the list get the keys ?

**Comment by diteix** [comment]
I get my keys!! Thanks!!!

**Comment by ivkanian** [comment]
can you give me one ;)

**Comment by K4NOMCAKEZ** [comment]
Thanks!! : 3

**Comment by MrMoua** [comment]
give me one :( lol. so sad

**Comment by 0ojookinzo0** [comment]
plz give me one :(

**Comment by Chaosbelow** [comment]
Please do not ask or beg for keys, especially multiple times. There will be many beta tests and then a release. You will play the game eventually.

**Comment by ghost** [comment]
FINALLY YYYY MY KEYS !

**Comment by emailboxu** [comment]
I've gotten mine. If you are ON THE LIST and you have not received a key, msg the admin on the official forums or open an issue for it. (Give it a few hours, the emails are taking a while to be sent.)

IF YOU ARE NOT ON THE LIST YOU WILL NOT RECEIVE AN EMAIL FOR 3 KEYS, THEY ARE ONLY FOR PEOPLE ON THE LIST IN THE FIRST POST.

**Comment by Chaosbelow** [comment]
@emailboxu Good to see you got your situation sorted out and got your keys ^^

**Comment by xKratoxx** [comment]
my heart is broken :'( need one

**Comment by ceddc** [comment]
@emailboxu 

> I've gotten mine. If you are ON THE LIST and you have not received a key, msg the admin on the official forums or open an issue for it.

 **Wait 4 hours before doing so.**

**Comment by Nsbld** [comment]
If only I knew korean... :<

**Comment by philfujisawa** [comment]
Someone who pick the key, has one for me? I contributed but without success. Thanks a lot guys!
Congrats!

**Comment by hasenbanck** [comment]
https://github.com/Treeofsavior/EnglishTranslation/commit/a93b9b161af05f099883e29561d12235e49a2baa

... 

People start to comment on old commits and try to beg for a key ...

**Comment by Spontaner** [comment]
Can someone give me a key pls ;S

**Comment by ceddc** [comment]
@hasenbanck  it's you commit, can't you delete his post?

people start e-mailing me begging for keys.
Direct to spam folder.

Beggars : go away.

**Comment by hasenbanck** [comment]
@ceddc Sadly I cant. I think that only the project owner can do so. IMCgames should sooner or later close and delete those comments / issue-threads. But let's wait until the storm is over. I think it will get worse for the next few days.

**Comment by Samusio** [comment]
Someone have one key for a fan of ragnarok and TOS ? =S , my heart cry

**Comment by nongnoobjung** [comment]
anyone share me pls i want translation to thai language

**Comment by xMiiNTY** [comment]
I can't believe it... I pass out in bed for 2 days because of an illness and miss out on beta :(

**Comment by Chaosbelow** [comment]
@xMiiNTY Try contacting STAFF_Marikim on the forums. You can also open an issue, they may make an exception!

**Comment by imcgames** [comment]
Hi @xMiiNTY 
You should be able to get the keys if you linked accounts since you are in the list. 
Please let me know if you weren't able to get the keys.

**Comment by xMiiNTY** [comment]
Thanks for the very quick reply imcgames <3
Yeah I have not received the keys, it says I'm not a beta tester on the treeofsavior.com website
I have contributed 190 lines all the way from April
But my problem was that I did not link my account until today (due to unavoidable circumstances)
The website also says that the limit is already reached

**Comment by ArkKnight** [comment]
Hi imcgames, I came to read the news a tid bit late, so I did not manage to link my github to your official site before 30/Jul. Any chances to get they keys or is it too late?

**Comment by imcgames** [comment]
@xMiiNTY  @ArkKnight  
Have you linked your account in website to github account? 
Can you link them and let the staff know? I'll try to check what we can do.

**Comment by xMiiNTY** [comment]
Yes, I've already linked my github account
How do I contact staff? The support tab on the website doesn't take me anywhere

**Comment by ArkKnight** [comment]
I have linked my Github account to the official site account.

**Comment by chewny** [comment]
I'd like a beta test key please. I have been linked for over a week

**Comment by laurencee** [comment]
@chewny Why would you get a beta key without having contributed anything? The beta keys here are for those who contributed 100+ lines to translation earlier on.

**Comment by kaleidliner** [comment]
can i get a key? i did contribute a few times to the direct korean translation?
