### ISSUE TITLE
tower of wizard => Magician's Tower [Reference is Mage Tower, so nevermind / close this]

### ISSUE THREAD

**Issue by Sourpusss** [Treeofsavior/EnglishTranslation#562]
The term "tower of wizard" and various derivatives are fairly common with quests involving the location.  However, occasionally the translation is correct and the lines refer to the place as "Magician's Tower."

I'm bringing this up as a way to agree of the proper term for the location, so I say we change all references to the place to "Magician's Tower" (as that sounds fairly regal, as well as it already appearing in the files).

**Comment by Sunaries** [comment]
I was the one who changed it to Magician's Tower, but somebody else came up with Mage Tower.

**Comment by Sourpusss** [comment]
Ah, I see.  Well, honestly, I vote for [the] Magician's Tower.  Aside from that and Mage Tower, we could also go with Wizard's Tower (however, that's a bit cliche, imo).

**Comment by Sourpusss** [comment]
Nevermind, I just realized the reference is actually "Mage Tower."

This being said, all "tower of wizard" references should be "Mage Tower."

**Comment by imcgames** [comment]
Mage Tower, yes :smile:
