### ISSUE TITLE
So do we still continue to translate and proof read?

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#563]
So do we still continue to translate and proof read? or continue after beta?

**Comment by vtange** [comment]
I'm still working. Just don't expect them to pull.

**Comment by Kxizen** [comment]
ok

**Comment by Gardosen** [comment]
i think they will also review your work and pull it, as they released a list with the names who qualified for the Keys.

**Comment by imcgames** [comment]
Yes, please do continue :smile:
