### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#564]
I'm getting an error when i try to submit lines that i have read over. i read like 200 lines and nothing saved because of error. -_-

**Comment by ttgmichael** [comment]
@Kxizen 
I think you just encountered a Merge conflict. What this means is that someone editted lines that you have editted and already pushed it into the main repository. As you don't have their edits on your lines, Github is unable to figure out how to merge your repository with the main repository. 

To solve this issue you first need to update your project with the main repository (after you commit your own changes to your repository).  BACKUP YOUR PROJECT first, then do a git pull to update your folder in your computer with the changes made in IMC's repository into your local drive.
After pulling, you will notice that changes have been made to the files in your hard drive. Your file will now have extra lines that have a bunch of equal signs and other stuff , these will be littered around the lines that you editted and also includes the lines from main repository (that was changed by someone else). You'll need to use your text editor and find those line conflicts (conflicts between your lines and someone else's lines.), then decide which one you want to have and delete the line you want to replace. 

A sanity check is to match the file's line numbers with its headers (For example, ETC.tsv, Line 4567 corresponds to ETC_20150317_004567). If there are misalignment, then there may be a line with merge conflction. Find these displaced lines and fix them.

**Comment by Kxizen** [comment]
Great! thanks for letting me know.
