### ISSUE TITLE
Tree of Savior Open Text Client available in beta?

### ISSUE THREAD

**Issue by ttgmichael** [Treeofsavior/EnglishTranslation#567]
Hooray that a lot of the contributors here got into the upcoming Beta. :)

Now the one thing that I want to just ask is whether the Open Text Client is available for this beta or not? If so, how will the changes be made to the main repository after beta? Can every tester change the text in game?

**Comment by Chaosbelow** [comment]
@imcgames This would be great to know. If the OTC is in I can have the people that I give the extra beta keys easily alert me of lines to proofread/edit. This could also help make translations a lot faster with better context and the ability for users to easily submit lines while playing.

**Comment by Pomez** [comment]
Agreed. There are times when I can't tell if a NPC is a he or she, or what subject you need to interact with in some quests. OTC would help greatly :grin:

**Comment by imcgames** [comment]
"The basic idea of OTC is to put all in-game text data into different language folders in the client"

If you are talking about having game text in the game client, yes, and the same files you see in Github will be used in the client. So if you make any edits by using your client, you can just send the edits to us through pull requests as usual.
If you are talking about real-time translation, it will be available as a beta version as well.
We will be posting details about the real-time translation later on :smile: 

Btw I feel like calling it real-time translation is kinda long, any suggestions on giving it a decent name? or should we refer to it as OTC as well? What ya guys think? :laughing:

**Comment by ttgmichael** [comment]
Ah, I meant real-time translation.  xD 
Thanks for letting us know that it's in the beta.
The name OTC is a good short abbreviation for real-time translation, or should it be in-game translations? which would be IGT. Though If you decide on OTC, it should be called a console rather than a client, so it isn't confused with the game client. ;)

**Comment by emailboxu** [comment]
@imcgames I think real time translation (abbreviated RTT?) is probably the best description for it as it clearly explains what it is. 

OTC = The client in which you can do RTT
(OTC) Repository = The text files on Github

I think that would clear up a lot of confusion.
