### ISSUE TITLE
Area Names

### ISSUE THREAD

**Issue by TOSBase** [Treeofsavior/EnglishTranslation#572]
I'd like to know how the Area Names are suppsoed to be called as it seems that there are some issues.

페디미안 직할령 is supposed to be Fedimian Territory
so i guess 직할령 is Territory in general?

However in the translation files it translated like this:
ETC_20150317_001141 페디미안 직할령
ETC_20150317_001141 Fedimian Area

so 직할령 would be Area.

ETC_20150317_001231 키렌 지방
ETC_20150317_001231 Kiren Province

This Area is not mentioned in the Wiki list.

ETC_20150317_001143 클라페다령
ETC_20150317_001143 Klaipeda Area

In the Wiki we it's called 클라페다 령 Klaipeda District

ETC_20150317_001238 칼리스 지방
ETC_20150317_001238 Kallis Province

This is like it's called in the Wiki :)

ETC_20150317_001262 별깃든 호수
xETC_20150317_001262    Starlit Lake Area

it's marked with an x but in the Wiki it's 별깃든 호수 Star-lit Lake Area

ETC_20150317_001217 로무바 성역
ETC_20150317_001217 Romuva Sanctuary

In the Wiki it's 로무바 성역   Romuva Sacred Precinct

ETC_20150317_001180 대삼림 지대
ETC_20150317_001180 Grand Forest Area

In the Wiki it's 대삼림지대    Grand Forest Region

ETC_20150317_001149 국왕직할령
ETC_20150317_001149 Royal Territory

same as in the Wiki

So are the ones in the Wiki correct or the ones in the translation files and is it intended to have similar names like Region, Area, Territory, District or should it be just one of them?

**Comment by ttgmichael** [comment]
IIRC, I felt it was a bit unnecessary to have the hyphen in Star-lit Lake Area so I shortened the name to Starlit Lake Area (it's easier to type as well). If we want to revert it back to Star-lit, we could do so. 

Aside from that, I think your question on how to name the locations will clear up when we actually get to play the beta.

**Comment by TOSBase** [comment]
Well, we already know pretty much what these areas are. The are collections of map. Every map belongs to an area you can even see it on the world map.

You cen see it here: http://www.tosbase.com/game/world-map/
If you move your mouse over one of the maps you'll not only see the map name but also the name of the Area (it's not up to date with current tanslations).
So Klaipeda Area are the start maps around Klaipeda and so on :)

**Comment by ttgmichael** [comment]
Oh I see. Then I think the translators are just trying to be consistent for now. As you stated, Areas == collections of smaller maps. So it doesn't really matter if these "Areas" change to Territory/Region/Field/Province right now (they are minor changes to me). We can make the changes to fit the wiki if people/ iMC agrees to it. I guess they would sound more fitting to their environment?

**Comment by imcgames** [comment]
We'll try to update the wiki next week :wink:
