### ISSUE TITLE
Accidentally linked my GitHub account to two accounts

### ISSUE THREAD

**Issue by Chaosbelow** [Treeofsavior/EnglishTranslation#573]
@imcgames I accidentally linked my GitHub account on the main website to two accounts. I messaged STAFF_Marikim on the forums but I am not sure I will get an answer back in time (before the 30th). I apologize for opening an issue but I would rather not cause confusion when trying to send the beta keys.

Thanks!

**Comment by imcgames** [comment]
Hi @Chaosbelow, STAFF_Marikim will be checking the message so let me know if you don't get a response by 31st.

**Comment by Chaosbelow** [comment]
Ok thank you!

**Comment by Chaosbelow** [comment]
Solved, thank you very much!
