### ISSUE TITLE
SKILL and UI

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#596]
Hey guys!

We've added the SKILL and UI files to the repository. 
We added them late because these files have to be handled a bit differently. 

For UI : 
There may be some translations that do not contain directly to its Korean text. 
This is so because we have to keep the translations as short as possible (especially for UI's) and we've made the adjustments after seeing them actually applied in game.
If your edits make the lines shorter, that's great, but if it doesn't, it's more likely that it should be kept as is. 

For SKILL : 
It contains a lot of tags so please make sure NOT TO EDIT THE TAGS.
Skill file still needs edits to make the lines shorter as much as possible. 

FYI, some terms still need to be retouched for consistency too. 
공격력 = ATK
방어력 = DEF
속성 = Property

**Comment by Nagoda** [comment]
It seems like editing parts of the UI will be much easier using the real-time editing tool in the game client, is that correct?

Being able to immediately see how it looks in-game should help a lot for preserving the formatting.

**Comment by imcgames** [comment]
Yup, that is correct and it's also why the file wasn't uploaded in github til now :smile:
