### ISSUE TITLE
[Forum] We can't login with FB\Gmail on the official forums

### ISSUE THREAD

**Issue by vegax87** [Treeofsavior/EnglishTranslation#597]
I can only login on the website with Gmail + Github but I can't login on the official forums as before, it display Login and Registration without support for Facebook\Gmail

What happened?

Other people have reported this issue: 
https://forum.treeofsavior.com/t/log-in-not-linked-to-fb-g-accounts-no-emails-received-for-password-issue/16915

**Comment by emailboxu** [comment]
Try logging into the official site, treeofsavior.com first and then going to the forum. Works fine for me.

**Comment by vegax87** [comment]
It doesn't work for me and other people, when I go on the forum I see this: http://i.imgur.com/IQcaDEb.png

**Comment by vegax87** [comment]
Seems OK now, If something goes wrong again I'll let you know.
