### ISSUE TITLE
Translation Corrected

### ISSUE THREAD

**Issue by choppaoops** [Treeofsavior/EnglishTranslation#599]
I'm new here, so just put this here.

SKILL_20150717_004739   Max HP and Physical DEF increase based on amount of [Plate] armor equipped and Attribute level. (Same weapon types from 3 ~).

This one should be: 

SKILL_20150717_004739   Evasion increases based on amount of [Leather] armor equipped and Attribute level. (Same weapon types from 3 ~).

**Comment by khakiout** [comment]
You can try to put it in a commit and perform a pull request. :+1:
