### ISSUE TITLE
Beta Schedule

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#601]
Sorry this is on the Github, but the Forum is currently laggy as hell because everyone is bombarding it to see if they got into the beta. Is the schedule starting from the 4th or the 3rd?

On the forum announcement it says the 4th, but in the email I got it said the 3rd.

**Comment by imcgames** [comment]
Hi @emailboxu it's the 4th.
For those who got email with 3rd, we'll be resending emails again with the correction.

**Comment by emailboxu** [comment]
Thanks for the confirmation.

**Comment by shankuzo** [comment]
Give me beta key please !! ;(

**Comment by erkanpurcu35** [comment]
give me Beta Key PLS

**Comment by rushein2013** [comment]
please send me beta keys TOS online, please i begging you, i want to play that game T_T 
rushein2013@gmail.com 
please sent me beta key
