### ISSUE TITLE
To all the keyless.

### ISSUE THREAD

**Issue by Kxizen** [Treeofsavior/EnglishTranslation#604]
Lets us all huddle and cry together. maybe if we cry hard enough we will all be blessed by the gods

:'(        ;'(   im so salty man

![889041-salt-man-2](https://cloud.githubusercontent.com/assets/13406664/9015884/608dccd2-379a-11e5-8e5a-16f25ff420f1.jpg)

**Comment by wlghksdl2** [comment]
Just means more time to translate. Take the hint from imcgames!
Back to staring at my toaster while watching streams.

**Comment by Chaosbelow** [comment]
This is not the place to post off-topic conversation. This should not be posted on the GitHub. This is the issue section where ISSUES are posted. So please keep it clean...

**Comment by emailboxu** [comment]
Please don't bring the key begging and crying to Github. This is not the place for it.
