### ISSUE TITLE
Instructions for making Tree of Savior read directly from the GitHub files

### ISSUE THREAD

**Issue by ensata** [Treeofsavior/EnglishTranslation#606]
Here is my method for making the game display the GitHub version of the files and allow you to edit and update changes much more quickly. 

If you want to use the GitHub files in the game without waiting for imc to update the patcher, your first idea is probably to copy-paste the files back and forth constantly between your download and the game's language folder, which is pretty tedious, and filled with risk. Instead, this is a trick I sometimes use that will **configure Tree of Savior to read files outside the Steam folder.** It might look complicated, but it's actually really simple.

With this, you can use all the features of GitHub while you're playing the game, instead of waiting for a transfer afterwards. You can switch branches, isolate and group your edits into them, and immediately upload changes or download the daily pulls. If you already know computers, then ignore this; I'm just making a symbolic link.

Also, I'm assuming that you have a copy of the files locally on your computer. You should have GitHub for Windows or whatever strikes your fancy. The synchronisation process doesn't change.
1. Take a note of where your GitHub files are on your computer. For me, it's `"G:\GitHub\ToS-en-fork"`
2. Look for where the game's language folders are placed on your computer. You should already see a folder named "English", but you'll want to make a new language folder. Figure out a name you want for the new folder, but _don't create it yet._
3. Take a note of the where the new folder is going to be, and its full name. For me, it's `"G:\Steam_Library\steamapps\common\TreeOfSavior\release\languageData\English_GitHub"`
4. Open up the command prompt — go to "Run…" and enter cmd.exe
5. Type this in: `mklink /d "the_new_folder" "the_folder_you're_pointing_it_to"`
   So, for me I'll type in `mklink /d "G:\Steam_Library\steamapps\common\TreeOfSavior\release\languageData\English_GitHub" "G:\GitHub\ToS-en-fork"`
   Don't forget the quotation markers.
6. If you go to %%\languageData\ you should now see a new folder, with a shortcut symbol. 
   This is not a standard shortcut, but a "symbolic link": it can be described as a sort of spoof folder that appears to be filled with stuff that programs can read and modify, but in actual fact, it's reading and modifying a completely different folder. If you delete this folder, the files on the other end will be safe. The files on the other end can be in a completely different location, or another drive.

That's it. The game should now have "English_GitHub" in the language options. Since the CBT hasn't started yet, you can modify it manually by opening user.xml and changing "Language". You can confirm the change by modifying the lines on the splash screen, which is in UI.tsv.

The alternative to all that stuff above is to simply move your git repo directly into the Steam folder, but it's an ugly method and there's all sorts of trouble associated with that. You can also just copy-paste the .tsv files, I suppose.

Whether or not you do this method, please be aware that **you actually can't use the GitHub files** until they have been cleaned. There are several things that need to be done on GitHub first:
1. All the x markers need to be removed, or you will get NoData errors and a huge number of merge conflicts.
2. All the remaining .tsv files should be added to the repo.

**Comment by ensata** [comment]
Well, that was a waste of time. Consider this your first bug report for the OTC.

After some further testing I've noticed that the game client will load the files behind a symlink just fine when it's started, but it won't update and reload the text if the file is updated mid-game. 

However, I can trick the game into reloading all the text by editing a file that isn't currently behind a symlink. In other words, as a step-by-step:
1. I set the game to read 'English_GitHub' (a folder behind a symlink), and load the game
2. Text appears fine.
3. I alter the text and save.
4. Nothing is reloaded in the game client.
5. I open, alter, and save a file in the 'English' folder.
6. The text is reloaded, displaying stuff from 'English_GitHub'.

If there's a hotkey or something to force the game to reload the text, that'd be great.

**Comment by imcgames** [comment]
Thanks for the instructions :+1: 
To supplement your post, you shouldn't have both Korean and English files in the same folder.

**Comment by laurencee** [comment]
I just cloned directly into the releases/languages directory (new folder called "Mine"), no need to mess around with junctions.

```
 TreeOfSavior\release\languageData>git clone <my_fork_link> <name_of_folder_I_want>
```

**Comment by ensata** [comment]
But I like making junctions! ... Well, it doesn't matter anymore anyway.
