### ISSUE TITLE
Haven't gotten keys yet. 

### ISSUE THREAD

**Issue by ttgmichael** [Treeofsavior/EnglishTranslation#609]
@imcgames, just making this issue to let you know I haven't recieved my keys yet. I'm part of the list in https://github.com/Treeofsavior/EnglishTranslation/issues/559

Oh and I should add that I have linked my github account to a forum account with the same name. xD

Will close this case when I get the email.

Thanks ^^

**Comment by imcgames** [comment]
Hi @ttgmichael ,
I'll try to have it checked and sent again after the weekend.
Very sorry for the inconvenience.

**Comment by imcgames** [comment]
@ttgmichael 
Please check your e-mail.

Thank you :)

**Comment by ttgmichael** [comment]
Thanks! :)
