### ISSUE TITLE
Item Descriptions and Flavor Texts: Too Long In-game

### ISSUE THREAD

**Issue by wlghksdl2** [Treeofsavior/EnglishTranslation#622]
From watching Korean ToS CBT3 streams with English Patch installed, I have noticed the following:

Item descriptions and flavor texts are too lengthy, overgrown with deadwood. For example, many of the descriptions begin "It can be used for..." or "It is..." or "This weapon is used for..." or other similar repetitive, boring variations.

I believe beginning the descriptions with nouns and pronouns is nothing but deadwood needing some good chopping. Much of it can be simply inferred by the accompanied Item Icons and other information available in-game. Not only does the verboseness clutter the UI, but it also harmfully contrasts the simple, yet charming, aesthetics of ToS.

For these reasons, I suggest the following edits:

"It can be used for..." -> "Used for..."
"A spear that is good for..." -> "Good for..."
"This weapon is used for..." -> "Used for..."  

Thanks for reading. Please comment and share your opinions.

**Comment by vtange** [comment]
For the most part we have been keeping a lot of text rough and wordy to keep it as literally accurate to the original Korean as possible. Thanks for the heads up.

**Comment by ttgmichael** [comment]
Yep! Most of the pull requests I do involve shortening these types of sentences in ETC.tsv to what you suggested. :)

**Comment by imcgames** [comment]
Yup. We've made adjustments in UI but most of it still seem to long. 
I'm sure we can get a better grip of things after the Beta Test this time so that it can be improved in future test phases. :wink:

**Comment by Nagoda** [comment]
@imcgames Are these item descriptions something that you would like editors to try to shorten, or are you guys going to attack it from the other direction by giving more space for text?
