### ISSUE TITLE
Foreign Translators

### ISSUE THREAD

**Issue by platymelon** [Treeofsavior/EnglishTranslation#652]
I'm sorry if I'm posting in the wrong place, but I was wondering if foreign translators will be receiving keys for testing too? I'm working for the Brazilian team and have translated around 1,400 lines myself however only one person in our team got recognition for their work and received a key. Thanks.

**Comment by vtange** [comment]
Unless you're absolutely sure you are working alongside imcGames to build an official Portuguese release, I would assume no. Sorry about that! Perhaps in the future? You and your team should keep a record of work to show imcGames in the future if you want recognition.

**Comment by hasenbanck** [comment]
There is no "Brazilian team" as far as imcGames is concerned. Right now there is only one official translation project (the English translation).

**Comment by platymelon** [comment]
I didn't mean to say we were an official team, we're just a bunch of passionate fans who want to bring as much as possible to the brazilian fan community of Tree Of Savior.(Although we are the the main fanpage for the country) Thanks for the replies.

**Comment by hasenbanck** [comment]
It's best to wait for now. Don't waste your resource by translating the english text into other languages yet. The english translations are currently in a constant flux and change far to often for you to use them for other languages.

Please close the issue.

**Comment by platymelon** [comment]
We're too far into it to just give up now. Thanks anyways

**Comment by ghost** [comment]
Keep working at it / save your work until IMC decides they're ready to support the rest of the European languages then hand them what you have.

**Comment by platymelon** [comment]
Will do. At least there will be something to build on for when they're ready for other languages :)
