### ISSUE TITLE
I want to contribute. I want to help. How?

### ISSUE THREAD

**Issue by christencodes** [Treeofsavior/EnglishTranslation#663]
I'm very new to GitHub and I want to contribute, but I'm kinda confused on how to help. I'm not sure if I'm supposed to comment or download something. I just want to contribute by fixing grammatical errors and Americanizing the text. Can someone help me with this GitHub thing?

**Comment by vtange** [comment]
Right now, if I were you, I'd start by just getting used to using Github. This weekend we had a large influx of grammar checkers and "Americanizers" and frankly, we don't need a whole lot of those people now cause it jumps the gun and risks losing information from the original Korean text before we even play the game and understand the context/etc. 

Learn. Github. Specifically, learn how pull requests, branches, etc. work and read all the guidelines. Here is a good one:

https://github.com/ensata/ToS-en-fork/blob/notes/GitHub_Usage.txt

So many new people (including me back then, actually) jump right in and end up conflicting with other,  more seasoned contributors and it really ticks them off. Thanks for holding back and asking first.
