### ISSUE TITLE
Real-time translation tool not working?

### ISSUE THREAD

**Issue by Nagoda** [Treeofsavior/EnglishTranslation#695]
Been playing the beta, and have not been able to get the real-time translation tool to work. The instructions say that shift+control+click on text will start up the tool, but I'm not getting anything. 

Is the tool supposed to be functional for this test? Has anyone else used it successfully?

**Comment by ThiefZero** [comment]
I'm not in the Beta, but it might be your text editor that isn't launching correctly.

**Comment by ttgmichael** [comment]
Mine doesn't work either. D:

**Comment by ghost** [comment]
The developers used Notepad++ in the screenshot, maybe it's looking specifically for that program? Do you guys have it installed?

**Comment by ttgmichael** [comment]
Yes. It's also my default text editor.

**Comment by imcgames** [comment]
I've posted how you can use the function for now before it is patched. 
https://github.com/Treeofsavior/EnglishTranslation/issues/705
