### ISSUE TITLE
How to enable Real Time Translation 

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#705]
Hey guys! 

You might notice that Real Time Translation is not yet enabled by default in game client for everyone. 
Therefore in the meantime, you can follow these steps to use the function. 

**A.** First, create a folder(ex. "kor") for _kor files in 
<< Tree of Savior Client Folder >> \release\languageData  
and place _kor files from the github repository in that folder ("kor")

By default, the client folder directory would be : 
C:\Program Files (x86)\Steam\steamapps\common\TreeOfSavior\release\languageData  

**B.** "editor.ini" was added to the repository. 
Place it in << Tree of Savior Client Folder >>\release\languageData  as well. 

So you should see something like this : 
![directory](https://cloud.githubusercontent.com/assets/11382705/9096487/621e7a8a-3bf8-11e5-8808-d8b8e896277e.png)

editor.ini : 
ReferLanguage => name of the folder in A
CommandOption => text editor .exe path, leave "[Path]" -n[Line]  as is 
(as much as possible, we recommend using Notepad++)

**C**. Restart the game.
Use Ctrl + Shft + Lef-click over the texts that you want to change in game using Real Time Translation.
<br>
**Important!**
'English' folder will be overwritten when the game is patched. 
So before you start editing with RTT, be sure to copy and create a backup of 'English' folder, rename the folder (ex. "Mine"), and choose your renamed folder name from the language option in game settings. 

![language](https://cloud.githubusercontent.com/assets/11382705/9096728/f4350b40-3bf9-11e5-93af-2471c8b916be.png)
<br>
<br>

**Comment by Sunaries** [comment]
Thank you for the instructions. It works wonderful. 
I have used this and made some changes to a few .tsv files. As a result of the Real Time Translation tool, I copied and pasted the entire files, hence why my new Pull Requests are large. ;;

**Comment by ensata** [comment]
Actually, the reason why your pull requests are large is because the GitHub version _still_ has the x marks and stuff. It's creating thousands of false positives in the diff generation and merge request. Until @imcgames removes it from the GitHub files and people stop adding them, the GitHub files and CBT files are fundamentally incompatible.

I said it right from the start that it was a bad idea.

**Comment by Sunaries** [comment]
@ensata I just looked at my submitted PRs and I only saw 3 or 4 x marks. Example: https://github.com/Treeofsavior/EnglishTranslation/pull/711 had 1 'ix' mark, but I've gone ahead and removed that.

**Comment by ttgmichael** [comment]
The large numbers should be expected, but easiliy solved; someone just needs to pull their translation files first and remove all the prefixes in the official repository. (could be anyone). Afterwards we can avoid making those marks while translating lines with the real-time translator.

**Comment by imcgames** [comment]
Our plan initially was to clear up pull requests, then merge it with the files you find in the client, and then updating the files in github with the files in client. 
In this case, it would have to be done after CBT since there are already too many PRs pending based on the pre-CBT translation file. (with some changes on matters related to marking as well)

But if we were to accept edits even during CBT period that are done using RTT,
I think what we can do is..

1) Close(not accept) all pending pull requests, and update the github with the same files you find in the game client
or
2) Open a temporary repository for CBT with same files you find in the client 

or we can just wait til after CBT to make the changes as we initially planned. 
So.. what do you guys think?

**Comment by Soukyuu** [comment]
1) sounds like the logical choice, 2) would mean you'd have to merge that repository into the current one again. Since contributors have to document their changes, it should be easy to port the changes over to the CBT client files.

**Comment by Sunaries** [comment]
@imcgames I forgot to tell you that my six pull requests are based of the .tsv from the \release\languageData\English folder. Not that of the Github repository. I only took the Korean files as instructed in this post.

I've made a lot of changes regarding to the UI, Help List, FAQs and did some changes based on the translation bug reports on forum.treeofsavior.com. I've also removed some x marks in a few files. With these changes, new players can understand the game better. Because a lot of sentences were poorly written. 

Here is a small album indicating some of the changes: http://imgur.com/a/sQteD

Also,

![](http://i.imgur.com/xaRuI4m.png)

I fixed the Rank & Char Lv. position. But I cannot fix this in item and skill descriptions. "Lv" and "x" are separate.

**Comment by imcgames** [comment]
So are we good with option 1?

**Comment by ghost** [comment]
I guess so. It's just a matter of resubmitting all the pull requests again after checking for conflicts, right?

**Comment by imcgames** [comment]
yup and for UI, as much as possible, the edits should be done using RTT not simply based on reading the text

**Comment by Sunaries** [comment]
My pending pull requests were all made by using RTT and based on the files from Steam version. This way I could check if the text was cut-off or not. So, I have to re-submit new pull requests again?

**Comment by imcgames** [comment]
I'd suggest resending your pull requests due to possible conflicts :wink:

**Comment by ttgmichael** [comment]
Option 1 it is!
Will close and resubmit and PRs I have ^^

**Comment by Sunaries** [comment]
@imcgames Alright. I'll resend my Pull Requests tomorrow with another batch of fixes from the translation reports on the forums. 😃

**Comment by imcgames** [comment]
be sure to check it with the latest githubs files too since the github files have accepted some pulls after being updated to client files. 
Currently, the state of files in github is (client files + fixes ) so you can take the files from github and use it in your client until it is patched.

**Comment by emailboxu** [comment]
Sorry I couldn't contribute to the RTT, I went to America to watch the DOTA2 International (literally the exact same week as the iCBT...) at a friend's house and didn't have my PC :(

Will there be another opportunity to contribute?

Edit; Also, do we need to rename the _kor.tsv files and remove the "_kor"?

**Comment by Sunaries** [comment]
@imcgames It's better if you close this and use the instructions in the README.
