### ISSUE TITLE
Character Limit Test Results (with Screenshots and other Typesetting Tests)

### ISSUE THREAD

**Issue by ensata** [Treeofsavior/EnglishTranslation#706]
Here are the results of some basic typesetting tests I did when I first logged in. 

I basically replaced any interesting UI element with standard placeholder text, with added character counts. The {nl} tag was not used at all, unless I say so.

First, a summary on important bits, and then pictures (I took over a dozen, and may have more later):
- All text appears to be left-aligned, non-justified. This includes the text inside floating boxes, which explains why @imcgames has been adding those weird margins. 
- Word wrap, width limits (ie. characters) and height limits (ie. no. of lines) all vary wildly. Many have dynamic heights, some are fixed, etc.
- Column width varies a lot, some dropping below 40 characters. (According to [this,](https://en.wikipedia.org/wiki/Line_length) the minimum comfortable reading width is 40 characters, with a maximum of ~75 for books, and ~100 for computer screens.) 
- Some essential Unicode punctuation is supported, but not much beyond that — This is actually dependent on the font file loaded.
  ![Dialogue Pangrams](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/unicode%20test.jpg)
- Dialogue boxes, oddly enough, have two word wraps — an automatic one at the margin, and a hardcoded one at every 120 characters. Long lines also goes into a new window.
  ![Dialogue Lorem Ipsum](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/dialogue.jpg)

Specific Images:
- [Character Creation](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/char%20creation.jpg) has a limit of **60 chars, 7 lines.** Summaries at the moment are only 2-3 lines, so there's a lot of room for additional flavor text.
- [NPC Names](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/dialogue%20pick.jpg) have a limit of **45 chars, with lines added with {nl}.** However, extra lines are left-aligned, so it should only be one line until it's fixed — Using an {nl} will make the next line get blocked by the button prompt icon and it will also be left-aligned in the bounding box, even though the element itself is centered.
- Dialog prompts (seen in the NPC Names screenshot) has a limit of **~60 chars, with one line.** Many, many lines are actually Player lines, which means quotation marks need to be added.
- [Help Bubbles](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/help%20bubble.jpg) have a limit of **30 chars, 2 lines.** Also, when the text was reloaded, it jumped upward for some reason, and jumped back down when reverted?
- [The Help Screen](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/help.jpg) has limit of **50 chars, with dynamic height.** The top blurb has a fixed limit of 4 lines. Also, for some reason the text on the list disappears when the .tsv files are altered. It's probably just a reload bug.
- [Loading Screens](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/loading.jpg) have **dynamic width and height,** with a centrally aligned box. However, the text is left-aligned. You might want to move it so the boxes have a consistent location. Also, based on the info, 'FAQ' should probably be 'Game Guide'.
- [Item Descriptions](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/item%20desc%20popup.jpg) have a width of **45 chars** and dynamic height, with good word wrap. 
- As per the last point, Item Names should not exceed **35 chars.**
- [Skill Descriptions](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/skill%20desc%20popup.jpg) have a limit of **35 chars**, and very large margins on the sides. Skill Data (the lower half) has a limit of **30 chars.** The entire window layout could be more compact.

_As per above, Skill Names should not exceed *_35 chars.**
- [Quest Info](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/quest.jpg) has a limit of **45 chars, with dynamic height.** The indent on the upper part could be a bit larger. This is the best looking one, but you can see that word wrap has trouble with long words.
- [Quest Info Hint](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/quest%20hint.jpg) has a limit of **40 chars with dynamic height,** and the Quest Name at **38 chars.** It still has the overrun problem. It looks like the word wrap margin is actually oversized to 45, even though the box is 40, since I see a 3 letter word (after the '80') is cut off.
- [Quest Clear](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/quest%20clear.jpg) has a limit of **45 chars,** like the other quest stuff.
- [Tooltips](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/tooltip%20with%201%20nl.jpg) have **infinite width, and no word wrap.** I used one {nl} tag for this picture. Also, it looks like tooltips are being abused throughout the game, since most windows have 6-7 line tooltips.
- [Dialogue Boxes](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/dialogue.jpg) have a limit of **90 chars,** but oddly enough, there's a **hardcoded line break at 120.** Based on a screenshot provided by imc a  few weeks back, this also proves that **the font size has been raised.** Also, you can see that an extremely long line will actually be cut off and continued in a new box.
- [Unicode and Full Alphabet test](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/unicode%20test.jpg) — a pangram is a phrase that uses the language's entire alphabet. You can see that all the basics for English and German are in here, as well as the basic Unicode punctuation that most people use. I used {nl}'s here, and you can see that there is actually a sixth line, that cuts off after one character. The character is repeated in the next window. Almost all Unicode failed, but this is usually caused by the font file that's loaded.
- [A shorter Unicode test](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/unicode%20test%20-short.jpg). The two failed characters in the second line are the reverse quotes, and I don't think anyone really uses those. Also, I have included a three-period-character ellipsis in the first line, while the second line has the Unicode ellipsis. You people debate far too much about them.
- [I also messed with my key bindings.](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/hotbar.jpg) It has a **character limit of 4.** It's usually not a surprise to get text overrun here, since there are so many keys, but there was a good call on using 's' instead of 'shift'. However, if you want the Numpad to be shown correctly, I recommend changing "NUMPAD#" to "NUM#". This is for mouse mode, by the way.
  ![hotbar](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/hotbar.jpg)

**Comment by ensata** [comment]
I found the book view. The width is **35 chars** which is far too small. You can see the entire Lorem Ipsum blurb I used, here, which means that a single page has a limit of 512 chars. The font needs to be smaller, or the window itself larger. I don't know where the line break above 'Nullam' comes from, since I didn't use any, but that's at the 425 char mark.

Also, there are a lot of books that only have one sentence per page over multiple pages, and the full space isn't really utilised. This is one of the places where you can add a ton of flavor text, so it's a bit of a shame.

![Book View](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/book%20view.jpg)

**Comment by imcgames** [comment]
Yup, books are indeed one of the places where you can add a lot of flavored text without having to worry about it affecting game play.

**Comment by ensata** [comment]
Issue's now obsolete, and closed.
