### ISSUE TITLE
One line not allow tsv format.

### ISSUE THREAD

**Issue by wazho** [Treeofsavior/EnglishTranslation#74]
https://github.com/Treeofsavior/EnglishTranslation/blob/master/ETC_en.tsv#L758

This line is not using TAB.

**Comment by Sunaries** [comment]
There is a pull request pending that will fix this syntax error: https://github.com/Treeofsavior/EnglishTranslation/pull/73

**Comment by wazho** [comment]
@Sunaries Thanks much :)
