### ISSUE TITLE
[Message to IMC] Add the Mark With "x" For Edited / Reviewed Lines to the Guidelines

### ISSUE THREAD

**Issue by Sourpusss** [Treeofsavior/EnglishTranslation#790]
I've noticed a lot of pull requests lately haven't been using the "x" system to mark edited / reviewed lines.  I thought this was going to be a standardized feature we agreed upon using, and having to inform a lot of new translators as to it is quite tedious.  I feel like if it was added to the Guidelines, a lot of people would take note of it and start using the system.

If this was not the case (in that it was agreed upon), we need to settle this matter, as such a feature is extremely important.

**Comment by Ragunaga** [comment]
Wait, it's only supposed to be edited lines? I was told after my last pull request that it had to be edited AND reviewed lines that were deemed fit for the game.

And i just submitted my lasted pull request like that q-q.

**Comment by Sourpusss** [comment]
No no, you're correct. I wasn't clear enough - I'll fix that.  But, see, it should be in the guidelines, lol.

**Comment by imcgames** [comment]
This was because during CBT, we were expecting edits only using RTT not based on reading them as we have it in the main page. 
As CBT is coming to an end, we'll have that added to guidelines.

**Comment by Soukyuu** [comment]
It is a bad idea to add an x in front of the line, as we have seen in CBT, as soon as next CBT starts, we will hit the same problem again. Instead of putting x in front of the line, you could put an x in front of the sentence instead, as in:

```
QUEST_JOBSTEP_20150317_000018   xGood. {nl}This research is being done together with the Bokor Master. So go pay her a visit and she'll tell you what to do. 
```

Or maybe use `#` instead for better legibility, unless the game parses that as some kind of tag

```
QUEST_JOBSTEP_20150317_000018   #Good. {nl}This research is being done together with the Bokor Master. So go pay her a visit and she'll tell you what to do. 
```

This way you won't have to remove all the markings every time a beta comes, and you can use the files directly in the game to edit them using RTT

**Comment by Ragunaga** [comment]
Removing the 'x's wouldn't be too hard. You can just search for "x(First letter of file name)" and replace all with (First letter of file name.)

**Comment by Sourpusss** [comment]
The current system is already in place, and seemingly the most efficient.  As @Ragunaga said, removing the x's isn't hard.  It would be much harder if the x's weren't infront of a uniform entry.  

Also, once again, the system is already in place.  It's increasing awareness that is the issue.

**Comment by Soukyuu** [comment]
Just because the system is in place doesn't mean it's efficient - besides, the x are currently not in place in the files. Every time you want to test the files in the game, you have to remove all x, then when you edit a line you have to somehow note it down and merge it with your x-ed copy. This is very cumbersome.

As for uniform entry, you can make one yourself, or choose a character that isn't used by the game like `$` - it is currently not used in any of the files. When the editing is done, removing the `$` is just as easy as replacing the x at the start, and it doesn't interfere with the ability to display the lines in the game and edit them live using RTT. You have to admit it is an advantage, especially with the amount of misplaced {nl} tags.

**Comment by ensata** [comment]
I've pointed out my disapproval of this system a few times already in other issues, and I really don't want to get into that detail again. This works as a hack, but hacks are meant to be temporary. We've already run into a bunch of problems with it, so a better system needs to be figured out sooner or later.

Adding the x marks will actually interfere with tracking changes via certain methods - also, the x marks were not completely scrubbed successfully for the CBT.

**Comment by Ihysoal** [comment]
Why is x both edited AND reviewed?
What is the marker for questionably translated text? Or suspected machine translation?

**Comment by Sourpusss** [comment]
Leave it unmarked, or edit it to an acceptable state.

and @ensata : When did it cause issues during the beta? And what methods do you speak of? What problems? You should bring them up so we can use them, and make corrections.  If you can think of a better system, let's use it.

I understand the Real-Time Translation tool is not going to work with the x's, but that system has yet to be implemented.  The x system is mostly there to prevent people from wasting time making arbitrary changes / reading over the same 200 lines.

**Comment by Soukyuu** [comment]
The RTT _is_ implemented, I was using it to do some of my edits during CBT. This was also the reason why the files had (most of) their x removed for CBT. Unless you mean the automatic submission part. 

I've also yet to read a reason why my suggestion of using `$` at the start of the message vs. x at the start of the line is inferior.

**Comment by Sourpusss** [comment]
Because it's arbitrary? If even that - it might be a huge negative. $ seems to be a feature of the games script, as if you haven't noticed, almost all errors are $NoData_XXXXXXXXX$

**Comment by Soukyuu** [comment]
Is it any more arbitrary than just putting an x instead? I don't think so.

I also don't think the game will be parsing a single `$` followed by text as a variable, it requires an opening and a closing `$` to get parsed as one. And even if - we can still use `§` instead, `$` was merely an example.

**Comment by Sourpusss** [comment]
Then I don't understand the problem with using x.  It's still a single character used at the beginning of the line.  It could be 5.  It doesn't matter - it's arbitrary.

**Comment by Soukyuu** [comment]
As I already said,
- if you place x at the start of the **text**, you can not search and replace all x to clean up, it's not unique enough
- if you place it at the start of the **line**, you have an unique pattern of xQUEST to search for, but it break the RTT/game because it won't be able to find the line, resulting in NODATA message.

My approach solves both of those.

**Comment by Sourpusss** [comment]
You search xPREFIX (xETC) and replace all with ETC.

Any symbol will do this.  If there is one that won't cause this issue, then obviously we should use it.  What makes you believe a $ won't mess it up?

**Comment by Soukyuu** [comment]
There seems to be either a miscommunication issue, or you're not reading what I'm writing.
This breaks the line in the game:

```
xQUEST_JOBSTEP_20150317_000018   Good. {nl}This research is being done together with the Bokor Master. So go pay her a visit and she'll tell you what to do. 
```

This doesn't, and stays searchable: replace '$' by '' (aka strip all occurrences of $).

```
QUEST_JOBSTEP_20150317_000018   $Good. {nl}This research is being done together with the Bokor Master. So go pay her a visit and she'll tell you what to do. 
```

And as you said, if $ is being parsed as variable, we can use §. I hope it's all clear now.

**Comment by Sourpusss** [comment]
Ah, I see.  I mean, if the character truly isn't used by the game, then we should use that system.  However, this system is only more effective if the character truly stays invisible, and requires no replacement.  Otherwise, it's still arbitrary.

**Comment by Ihysoal** [comment]
You can just search for newline+x and replace every x at the start of a line in every file easily.

**Comment by Soukyuu** [comment]
Yes you can. And you will have to do that every time you want to see the result ingame. Then painstakingly put all of them back, risking to forget one, or alternatively, having to manually merge your new versions edited through the RTT back into the x-ed file.

@Sourpusss: The character won't stay invisible, of course. I have stated why this is a better approach several times already, I feel like I'm talking to a wall here. IMCGames stated they will look at whether that work in another issue, so I don't think any additional posting is required on my part.

**Comment by Sourpusss** [comment]
"it doesn't interfere with the ability to display the lines in the game"

All I'm saying that the change is arbitrary, and is just as easy to remove as the current system, of which some people are already used to using.

**Comment by Soukyuu** [comment]
The change would only be arbitrary if it didn't bring anything positive to the table, which it does: you **don't** have to remove the character. A single § in front of the sentence might look distracting at first ingame, but as it's only a temporary marker which will be gone after editing, it doesn't interfere with your ability to edit and display the line from within the game.

In fact, you could even reverse the system and mark lines needing editing with that special character. So once you see the § you know that line isn't done yet. That way, you could also avoid breaking the line breaks, should the text happen to not line break as expected with the character added.
