### ISSUE TITLE
Discord - Another way of communicating with each other

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#825]
**What is Discord?**
[Discord](https://discordapp.com/) is a new VoIP app that is free to use. There are no costs for servers, accounts, etc. 
You can also use Discord from mobile apps, desktop apps, or just through the browser.​ It is a very good alternative to Skype. (It doesn't hog your CPU as Skype does...)

 I set up a server. GitHub contributors are welcome to join. [Click here to join the Discord server.](https://discord.gg/0RoYSiES4f4zwAk8)
If you have questions regarding a certain translation or about something else, you can ask others who are online in the room. There are separate text channels (ETC, ITEM, QUEST etc.) where you can discuss about the translation. 

Hope to see you soon.

**Comment by Ihysoal** [comment]
Discord seems a way for the more dedicated translators to get together and communicate with each other. Is it time for imcgames to just take in these more dedicated translators as a (volunteer) team that works on establishing standards and guidelines for other smaller contributors to follow?

Barely anything gets done with all the slow discussion in terms of establishing those guidelines or standards, thanks to the "too many cooks in the kitchen". Or am I seeing this wrong?

**Comment by Sunaries** [comment]
We have a few contributors checking in the server. :) It is indeed a good place for dedicated translators to get together.

**Comment by ttgmichael** [comment]
I like the idea! Joining ^^
It'll be even better if IMC joins too xD

**Comment by Requinn** [comment]
Was highly considering this too. Glad to see someone else thought the same.

**Comment by Requinn** [comment]
aaaand server is down for an update at the moment.

**Comment by ttgmichael** [comment]
I'm not acquanted with Discord, so I'm kinda stuck with the logo spinning. Is your server down @Sunaries ?

When should people gather time wise? I'm in Pacific Standard Time.

**Comment by Requinn** [comment]
The whole service was down for an update. It should be up now? (at least for me)

**Comment by ttgmichael** [comment]
Looks like its on now ^^

**Comment by Sunaries** [comment]
Closing this Issue since users can join the Discord by clicking on the link addressed [here](https://github.com/Treeofsavior/EnglishTranslation/issues/850)
