### ISSUE TITLE
Healer Lady vs. Pharmacist lady NPC

### ISSUE THREAD

**Issue by Soukyuu** [Treeofsavior/EnglishTranslation#828]
There is an inconsistency with the "Healer Lady" NPC in Miners' Village: 
- before finishing the quest chain with her in the western field, she is referred to as "Healer Lady" by the quest text/objectives
- after finishing the quest chain, the same NPC is present in the village itself, but now has the name "Pharmacist lady".

Which one should we be going with? Personally leaning towards "Healer Lady", because she seems to be casting magic on the wounded soldier.

**Comment by Sunaries** [comment]
Healer Lady.

**Comment by Soukyuu** [comment]
Healer Lady it is.
