### ISSUE TITLE
A Soldier's Favor quest: Keepsakes vs. relics vs. memento

### ISSUE THREAD

**Issue by Soukyuu** [Treeofsavior/EnglishTranslation#829]
One of the repeatable quests in Miners' Village refers to the items you need to gather as "keepsakes" (QUEST_LV_0100_20150317_003809), the quest objective refers to them as "memento of soldiers" (QUEST_LV_0100_20150317_006351), while the item itself is called "Soldiers' Relics" (ITEM_20150317_003916).

"Relic" doesn't make much sense unless you are gathering their remains, which is kind of morbid, but then "remains" is a more common word. If it's not the intended meaning, then maybe using "memento" or "keepsake" (which one is more common?) would be more appropriate.

**Comment by Sunaries** [comment]
Let's stick with one term for consistency. It should be **Keepsake** and not keepsake**s**, because there is one keepsake.

**Comment by Soukyuu** [comment]
You actually gather 6 or 10 of them, so "keepsakes" referring to all 10 of them would be valid.

**Comment by Sunaries** [comment]
> You actually gather 6 or 10 of them, so "keepsakes" referring to all 10 of them would be valid.

Based on the lines you provided, I didn't see the plural of keepsake in the Korean counterparts.  Anyway, it should be keepsake and not memento or relic. :smile:

**Comment by Soukyuu** [comment]
And keepsake it is.
