### ISSUE TITLE
Mass replacement of ellipsis (...) with the ellipsis specific character (…)

### ISSUE THREAD

**Issue by Ihysoal** [Treeofsavior/EnglishTranslation#830]
Should it be done? I honestly don't see why not.

**Comment by ensata** [comment]
I really don't care. 

They're typically compatible with each other and recognised as the same thing, so it's mostly just a programming and typesetting problem. Some pull requests have been reverting the ellipsis character to the three periods, too.

The main difference is in a spacing of a few pixels, and there are compatibility reasons for using one or the other, and there's no major advantage. If there's a problem with one, you just switch to the other one. I personally do the specific character as a way to prevent typos and measure my character count better.

**Comment by Sourpusss** [comment]
No - it was agreed upon by IMC that the normal "..." (three period, non-unicode) ellipses should be used).

**Comment by imcgames** [comment]
Let's not touch ellipsis for now :)
We will replace them if the need arises.

**Comment by laurencee** [comment]
One of the unicode ellipses displays vertically centered in the client so you'd have to make sure that isn't the case for whatever one you were using.

But as IMC has already said, no need to touch for now.
