### ISSUE TITLE
Very outdated pull request

### ISSUE THREAD

**Issue by Requinn** [Treeofsavior/EnglishTranslation#834]
So last week before iCBT I made a pull request (#662) with a bunch of changes and translations for quest_lv_200.tsv. Now that a bunch of people have made changes to some affected lines and whatnot, should I leave it or remake a pull request with the changes? A few of the lines in that one also have changes in newer PRs regarding the file. 
I'm also wanting to translate more of the file, but can't make edits until this is solved.

**Comment by imcgames** [comment]
Since the files have been chaged during CBT, as much as possible, it'd be best to close them and submit a new one uing the updated files

**Comment by laurencee** [comment]
If you want to create multi pull requests then you should not do your changes off your master branch, you should instead create a branch for each change and then submit a pull request off those branches. This keeps the changes isolated.

You can then keep those branches up to date by rebasing from the official translation repo which will prevent having lots of "merge" commits listed in the pull request.

Here's a nice guide that's appropriate: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
