### ISSUE TITLE
Too many cooks

### ISSUE THREAD

**Issue by cordogames** [Treeofsavior/EnglishTranslation#844]
Far too many cooks on this project right now.

An important part of contributing to a translation project is to cross-reference what you're going to work on with what's currently opened as a pull request. If you really need to get a change in on a line that's already being worked on, just comment on the opened pull.

If the opened pulls are outdated, then that's another thing.

**Comment by ttgmichael** [comment]
While I agree that people need to cross-reference what is being done, I think there is a better way to solve this; the "Too many cooks" should only a problem if we are disorganized and making PRs that are too big (therefore increasing the likelihood that there will be overlap).

We need to communicate better and figure out who's doing which lines before these types of conflicts arise. @Sunaries started a Discord server for us to better communicate which lines we will be working on.

**Comment by emailboxu** [comment]
It's only a clusterf--- if we don't organize roles and areas to translate for people. The Discord server should fix that.
