### ISSUE TITLE
Starting on line 3016 of QUEST_JOBSTEP_kor.tsv there are tags that are not in the eng version.

### ISSUE THREAD

**Issue by Ragunaga** [Treeofsavior/EnglishTranslation#878]
The tags that start at the front of a line, like QUEST_JOBSTEP_######_####. The tags lead to both Accept and Reject on Quest_Lvl_100 and 200.

They're not on the english version, and I seemingly have no idea what to do with em. Any input from someone who knows what they are? IMC maybe?

**Comment by imcgames** [comment]
Ah, those should have been removed. 
I'll have it removed and update the file.
