### ISSUE TITLE
SKILL.tsv - Shrink Body

### ISSUE THREAD

**Issue by vegax87** [Treeofsavior/EnglishTranslation#901]
SKILL_20150317_002217   Movement of enemy shrinked with [Shrink Body] **increase** by 5% per attribute level and Physical, magic attack **increase** by 10% per attribute level.

I wonder if this is a  translation error or it's designed as it is, a shrinked body should have more movement speed and less physical\magical attack, because it's strange to give a buff to an enemy, it makes no sense at all....

**Comment by Flevalt** [comment]
The movement speed change in this attribute description is correctly stated as increase.
But the damage increase is actually a decrease. It should say "decrease by 10%"

If you enlarge the body it gets slower but stronger.
If you shrink the body it gets faster but weaker.

**Comment by imcgames** [comment]
Yup, that line was wrong. It should be : 
Movement of enemy shrinked with [Shrink Body] increase by 5% per attribute level while Physical, magic attack decrease by 10% per attribute level.
