### ISSUE TITLE
Silver vs Silvers for currency denotation.

### ISSUE THREAD

**Issue by Ragunaga** [Treeofsavior/EnglishTranslation#905]
This is something I've been noticed going on for awhile, a lot of people have started changing "Silver" , in reference to the currency/money for ToS, to "Silvers." While both are technically correct we need to decide on one right here and now before more people start changing this, and it becomes multiple things in multiple areas.

Silver is the plural of liquid and or ore silver most of you are common with. There's no questioning that.

It comes into question when you are talking about coins made of the silver. Generally the plural will remain the same, but some will argue that since you are talking about multiple single coins that you should fall back to the general english plural form of adding an s; Silvers.

I believe we should stay at the form generally in use for it right now, Silver. It slides off the tongue nice, is easy to say, and makes sense to me.

**Comment by Soukyuu** [comment]
I agree, "Silvers" just sounds wrong. Voting for keeping "Silver".

**Comment by Nagoda** [comment]
I don't think there's much debate here. You would never be caught dead saying "Pay me ten Golds".

I'm not sure about the specific etymology of this usage, but It's definitely just Silver.

**Comment by Flevalt** [comment]
It stays "Silver", even in plural form.

If you feel you absolutely have to avoid using "Silver" in order to avoid misconceptions, you could write "Silver Coins". But I can only think of few scenarios where that would be preferrable over "Silver".
