### ISSUE TITLE
Doubt about UI.tsv - line 755

### ISSUE THREAD

**Issue by ghost** [Treeofsavior/EnglishTranslation#913]
In line 755 of UI.tsv,
The actual setting [Select Language] is using a white font and you barelly can see it.
The original code is [UI_20150317_000755    {@ St43}{b}             Select Language {/}{/}]
![screenshot_20150824_00003](https://cloud.githubusercontent.com/assets/12136149/9437653/2ef1694e-4a2e-11e5-8a32-e35b7757a29d.jpg)

Is it was supposed to be white as above?
I know it was supposed to be in the center, but if you use [{@st43b}Select Language{/}], the font will be like this:

![screenshot_20150824_00002](https://cloud.githubusercontent.com/assets/12136149/9437661/3b738f12-4a2e-11e5-9431-f2fb91cc39e3.jpg)

So I really want to know if it is right or wrong.

**Comment by imcgames** [comment]
Yes, the space between @ and S in '@ St43' was meant to be removed. 
Thanks for pointing that out. We'll have it changed.
