### ISSUE TITLE
Need translation help: QUEST.tsv lines [1158-1235, 1435-1436, 1447-1448, 1461]

### ISSUE THREAD

**Issue by terrapin47** [Treeofsavior/EnglishTranslation#922]
Please reference #916.  The lines [1158-1235, 1435-1436, 1447-1448, 1461] are in need of proper translation.  Any help would be awesome.

**Comment by vtange** [comment]
@Senhart Are you capable of translating from scratch? Or should I hop back from QUEST lv100?

**Comment by ghost** [comment]
Oh no, I'm not. Please do.

**Comment by vtange** [comment]
This Issue can be closed once ^ these PRs are pulled.

**Comment by terrapin47** [comment]
@vtange Awesome, thanks!
