### ISSUE TITLE
Usage of 'ea'.

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#929]
So, we've had 2 Issues regarding the usage of 'ea'. @imcgames has said the following on this issue: _"Thank you for your suggestions. This has actually been discussed internally for a while and we are in progress of changing it to use variables._"

Meanwhile, I've submitted a Pull Request today https://github.com/Treeofsavior/EnglishTranslation/pull/925 where I changed the format of obtaining an item. Currently, I like @ensata's suggestion of using ×. Please remember that even though I used this, it does not mean this is final and can always be easily edited. 

Take a look at this imgur album for a few screenshots for possible alternate options: http://imgur.com/a/L7tyi

Let me know your thoughts.

**Comment by terrapin47** [comment]
I like this change.  The usage of 'ea' or 'each' in this and other games was always uncomfortable in English.  "2 each obtained", or just "2 each" is a strange way to say that there are 2 of the item.

**Comment by BloodHeartless** [comment]
"x" and the number obtained is the best way...

**Comment by Soukyuu** [comment]
As said on discord, I'm for the `×1` formatting.

**Comment by ttgmichael** [comment]
As shown on my wiki and Discord, I like the ×1 formatting as well.

**Comment by grillo-delmal** [comment]
I actually like (1) on the right side of the text, but I suppose i'm a minority :)

**Comment by f-tsang** [comment]
In the end, it boils down to personal preference. Though, changing the 'ea.' thing is definitely necessary.

@zhouyu47 Most of the time it's not just an awkward usage of 'each', but incorrect as well.

@Grillo-del-mal I prefer ×1 on the right side ;)

**Comment by Nagoda** [comment]
Definitely a proponent of the "×" format for the pickup notification. Other instances of "ea" will probably need their own solutions depending on context. Only minor change I would make is I think it looks better with a space after the ×,

Item × 1 obtained
vs
Item ×1 obtained

**Comment by Sunaries** [comment]
> Definitely a proponent of the "×" format for the pickup notification. Other instances of "ea" will probably need their own solutions depending on context. Only minor change I would make is I think it looks better with a space after the ×,

Item × 1 obtained
vs
Item ×1 obtained

@Nagoda Like this? 

![GitHub Logo](http://i.imgur.com/qhsdn8d.jpg)

**Comment by imcgames** [comment]
Yup, 'x' seems better than ea.

**Comment by Soukyuu** [comment]
Personally, this looks ugly:

> Item × 1 obtained

I very much prefer it to be without the space

> Item ×1 obtained

**Comment by ghost** [comment]
I vote for without space too.
