### ISSUE TITLE
Skill Name [ Cartar Stroke ] - 카타스트로크

### ISSUE THREAD

**Issue by terrapin47** [Treeofsavior/EnglishTranslation#943]
@imcgames, could you shed some light on what this skill name is supposed to mean?  The words 'Cartar Stroke' don't make much sense in English, and typically the skill names in the swordsman tree make sense in either English or German.

The skill itself involves the swordsman performing an overhead swing that hits enemies in a line ( multiple hits ) and pushes them.  There is also a collision effect, where if the enemies are pushed into a wall ( or into other enemies? ) it does extra damage.

**Comment by Nagoda** [comment]
I noticed this in the beta as well. It's also very inconsistent and It's not clear which version was even intended between "Cartar Stroke", "Catar Stroke", or "Catastroke".

**Comment by grillo-delmal** [comment]
https://translate.google.com/#ko/en/%EC%B9%B4%ED%83%80%EC%8A%A4%ED%8A%B8%EB%A1%9C%ED%81%AC

If you push the "listen" button in the Korean word, it hears "Catastroke"... maybe it's a word play between the words "Stroke" and "Catastrophe"

**Comment by ttgmichael** [comment]
Haha, that'd be an interesting origin ^ xD (it does sound like Catastrophe a bit)

**Comment by Requinn** [comment]
http://imgur.com/5lklHZz.png

 (source: http://aaoema.com/Two-Hand-Sword-Translation-SECURE.pdf 
*this is a translation of Harleian text regarding Two-Handed Sword technqiues.)

**Comment by imcgames** [comment]
Cartar Stroke is its intended skill name. 
The name 'Cartar Stroke' comes from an old British sword technique which is also sometimes referred to as Carter's Stroke (depending on which book you read.) 
Also, you may have guessed from the name but it is speculated to be called such because its action resembles a carter's use of the whip.

**Comment by terrapin47** [comment]
Ah, interesting.  Thanks!
