### ISSUE TITLE
Is "Repair Weapon" translation wrong?

### ISSUE THREAD

**Issue by ghost** [Treeofsavior/EnglishTranslation#950]
Is this translation wrong or misplaced? The guy was upgrading/refining the Bow and giving it some buffs on minimum and maximun attack, though, he is not repairing the weapon.

("Repair Weapon" at top-left corner of the window)

![screenshot_20150829_00009](https://cloud.githubusercontent.com/assets/12136149/9568798/84e51ef2-4f2b-11e5-8969-d8bdea544903.jpg)

**Comment by Sunaries** [comment]
This should be "Weapon Maintenance" - I already fixed this in a pending PR: https://github.com/Treeofsavior/EnglishTranslation/pull/944.

**Comment by ghost** [comment]
Oh, much better. Thanks c;

**Comment by Sunaries** [comment]
If your PR has been answered, please close it. @huenato  :)
