### ISSUE TITLE
Feedback: Skills

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#991]
Greetings,

I've been working on the SKILL.tsv file to iron out the mistranslations, typos and errors. While this is still a work in progress, I've discovered another big task to accomplish good readable skills and descriptions. Which is moving around the original Korean text, because currently the tooltip where it says what the skill does is a mess. It needs to be cleaned. 

However, there are currently two ways (possibly more) of laying it out:

![GitHub Logo](http://i.imgur.com/VkKSrhE.png)

Unfortunately, at this moment I cannot do anything about "**X** Level" since that is a coding issue.

Which option do you prefer and would like to see it ingame? Please give me your feedback. I have also posted this on the [official forums](https://forum.treeofsavior.com/t/feedback-skill-descriptions/40242).

**Comment by Soukyuu** [comment]
I'd go with 1, but:
- "Number of tiles: 1" instead of "Firewalls: 1", the whole thing is a fire wall, else people might confuse it with being able to cast x fire walls at the same time.
- "Number of hits: 6" instead of "Number of attacks: 6", "attacks" sounds more active, kind of.

2 is nice as well, but has the problem of inflexible number. Personally, I don't like the look of "Fire Wall(s)"

**Comment by ghost** [comment]
My vote goes to No. 1 but with the changes mentioned above.

**Comment by Requinn** [comment]
I'd go with #1. @Soukyuu has it down for the other changes. I'd also change '5 Level' to 'Level 5' though.

**Comment by vtange** [comment]
Go with #1, change '5 Level' to 'Level 5' as @Requinn mentioned
Do you get multiple Fire walls per level or does the fire wall cover more tiles? If former then "Number of Firewalls: 3', if latter then go with what @Soukyuu said.

**Comment by f-tsang** [comment]
@vtange If this video is anything to go by, I'd say leveling it up will increase the number of tiles covered.

> [![YouTube - ToS Fire Wall](https://i.ytimg.com/vi_webp/gLjj30Wt80w/hqdefault.webp)](https://www.youtube.com/watch?v=gLjj30Wt80w)

I too prefer "Number of tiles: 3" as @Soukyuu mentioned.

Edit: My comment was previously unclear/misleading. Sorry about that!

**Comment by Soukyuu** [comment]
Yes, it increases the number of tiles (I played pyromancer in the iCBT).
@ftsang92: I think you read his message wrong, he said to change it to "tiles" if it increases tile count.

**Comment by Xenobius2501** [comment]
I'd probably say #1 with aforementioned fixes as well, and we could even shorter it a bit to
"Tiles: ?"
"Hits: ?"

But that one's a matter of taste, I guess.

**Comment by imcgames** [comment]
Well, if the majority prefers #1, let's go with #1 then :smile: 
As for the issue on 'X Level', it seems it's coded that way since that's how Korean works but we'll have it checked with the devs.

**Comment by Sunaries** [comment]
Alright, #1 it is! Thank you. :smile:

**Comment by Soukyuu** [comment]
@imcgames: Just a suggestion for the cases of "coded that way". You could have a line with the following template:

```
text{tag}text
```

so that for the Korean files, you use

```
{tag}text
```

and for the English files, we could use

```
text{tag}
```

It would solve a lot of problems if we had this. Please consider changing lines that are affected to this.

**Comment by imcgames** [comment]
@Soukyuu 
Yup, that is actually how things are done nowadays.
Just seems like there are still some parts left from the earlier days of development where grammar difference between languages wasn't considered so much but we are trying to change them as we spot them or when the need arises. :wink:

**Comment by Soukyuu** [comment]
Should we make an issue to collect such lines? Some UI messages come to mind (like "<item name> is not enough")

**Comment by vegax87** [comment]
I vote # 1

**Comment by imcgames** [comment]
@Soukyuu  
that'd be very helpful :+1:
