### ISSUE TITLE
ITEM 20150717_005556 - 005569 missing?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [Treeofsavior/EnglishTranslation#998]
I'm not sure if I did something wrong, but I can't seem to find ITEM 20150717_005556 - 005569. It has been merged. Should I do another pull request?

**Comment by imcgames** [comment]
Oh, I'll try to check those lines and add them back in. 
Thanks for pointing that out :+1:

**Comment by WorksWellWithOthers** [comment]
Thank you.
